// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oioio-space/maldev/internal/manager/store/ent/identity"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// IdentityUpdate is the builder for updating Identity entities.
type IdentityUpdate struct {
	config
	hooks    []Hook
	mutation *IdentityMutation
}

// Where appends a list predicates to the IdentityUpdate builder.
func (_u *IdentityUpdate) Where(ps ...predicate.Identity) *IdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *IdentityUpdate) SetName(v string) *IdentityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableName(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *IdentityUpdate) SetBytes(v []byte) *IdentityUpdate {
	_u.mutation.SetBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *IdentityUpdate) SetSha256(v string) *IdentityUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableSha256(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the IdentityMutation object of the builder.
func (_u *IdentityUpdate) Mutation() *IdentityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdentityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdentityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := identity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Identity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bytes(); ok {
		if err := identity.BytesValidator(v); err != nil {
			return &ValidationError{Name: "bytes", err: fmt.Errorf(`ent: validator failed for field "Identity.bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := identity.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "Identity.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *IdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(identity.Table, identity.Columns, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(identity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(identity.FieldBytes, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(identity.FieldSha256, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{identity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdentityUpdateOne is the builder for updating a single Identity entity.
type IdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdentityMutation
}

// SetName sets the "name" field.
func (_u *IdentityUpdateOne) SetName(v string) *IdentityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableName(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *IdentityUpdateOne) SetBytes(v []byte) *IdentityUpdateOne {
	_u.mutation.SetBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *IdentityUpdateOne) SetSha256(v string) *IdentityUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableSha256(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the IdentityMutation object of the builder.
func (_u *IdentityUpdateOne) Mutation() *IdentityMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdentityUpdate builder.
func (_u *IdentityUpdateOne) Where(ps ...predicate.Identity) *IdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdentityUpdateOne) Select(field string, fields ...string) *IdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Identity entity.
func (_u *IdentityUpdateOne) Save(ctx context.Context) (*Identity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdentityUpdateOne) SaveX(ctx context.Context) *Identity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IdentityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := identity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Identity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bytes(); ok {
		if err := identity.BytesValidator(v); err != nil {
			return &ValidationError{Name: "bytes", err: fmt.Errorf(`ent: validator failed for field "Identity.bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := identity.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "Identity.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *IdentityUpdateOne) sqlSave(ctx context.Context) (_node *Identity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(identity.Table, identity.Columns, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Identity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, identity.FieldID)
		for _, f := range fields {
			if !identity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != identity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(identity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(identity.FieldBytes, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(identity.FieldSha256, field.TypeString, value)
	}
	_node = &Identity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{identity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
