// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/issuer"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// IssuerQuery is the builder for querying Issuer entities.
type IssuerQuery struct {
	config
	ctx          *QueryContext
	order        []issuer.OrderOption
	inters       []Interceptor
	predicates   []predicate.Issuer
	withLicenses *LicenseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssuerQuery builder.
func (_q *IssuerQuery) Where(ps ...predicate.Issuer) *IssuerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IssuerQuery) Limit(limit int) *IssuerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IssuerQuery) Offset(offset int) *IssuerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IssuerQuery) Unique(unique bool) *IssuerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IssuerQuery) Order(o ...issuer.OrderOption) *IssuerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLicenses chains the current query on the "licenses" edge.
func (_q *IssuerQuery) QueryLicenses() *LicenseQuery {
	query := (&LicenseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issuer.Table, issuer.FieldID, selector),
			sqlgraph.To(license.Table, license.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, issuer.LicensesTable, issuer.LicensesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Issuer entity from the query.
// Returns a *NotFoundError when no Issuer was found.
func (_q *IssuerQuery) First(ctx context.Context) (*Issuer, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issuer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IssuerQuery) FirstX(ctx context.Context) *Issuer {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Issuer ID from the query.
// Returns a *NotFoundError when no Issuer ID was found.
func (_q *IssuerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issuer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IssuerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Issuer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Issuer entity is found.
// Returns a *NotFoundError when no Issuer entities are found.
func (_q *IssuerQuery) Only(ctx context.Context) (*Issuer, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issuer.Label}
	default:
		return nil, &NotSingularError{issuer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IssuerQuery) OnlyX(ctx context.Context) *Issuer {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Issuer ID in the query.
// Returns a *NotSingularError when more than one Issuer ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IssuerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issuer.Label}
	default:
		err = &NotSingularError{issuer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IssuerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Issuers.
func (_q *IssuerQuery) All(ctx context.Context) ([]*Issuer, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Issuer, *IssuerQuery]()
	return withInterceptors[[]*Issuer](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IssuerQuery) AllX(ctx context.Context) []*Issuer {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Issuer IDs.
func (_q *IssuerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(issuer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IssuerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IssuerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IssuerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IssuerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IssuerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IssuerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssuerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IssuerQuery) Clone() *IssuerQuery {
	if _q == nil {
		return nil
	}
	return &IssuerQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]issuer.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Issuer{}, _q.predicates...),
		withLicenses: _q.withLicenses.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLicenses tells the query-builder to eager-load the nodes that are connected to
// the "licenses" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IssuerQuery) WithLicenses(opts ...func(*LicenseQuery)) *IssuerQuery {
	query := (&LicenseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLicenses = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Issuer.Query().
//		GroupBy(issuer.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IssuerQuery) GroupBy(field string, fields ...string) *IssuerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IssuerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = issuer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Issuer.Query().
//		Select(issuer.FieldName).
//		Scan(ctx, &v)
func (_q *IssuerQuery) Select(fields ...string) *IssuerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IssuerSelect{IssuerQuery: _q}
	sbuild.label = issuer.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IssuerSelect configured with the given aggregations.
func (_q *IssuerQuery) Aggregate(fns ...AggregateFunc) *IssuerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IssuerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !issuer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IssuerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Issuer, error) {
	var (
		nodes       = []*Issuer{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withLicenses != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Issuer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Issuer{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLicenses; query != nil {
		if err := _q.loadLicenses(ctx, query, nodes,
			func(n *Issuer) { n.Edges.Licenses = []*License{} },
			func(n *Issuer, e *License) { n.Edges.Licenses = append(n.Edges.Licenses, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IssuerQuery) loadLicenses(ctx context.Context, query *LicenseQuery, nodes []*Issuer, init func(*Issuer), assign func(*Issuer, *License)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Issuer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.License(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(issuer.LicensesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.issuer_licenses
		if fk == nil {
			return fmt.Errorf(`foreign-key "issuer_licenses" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "issuer_licenses" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *IssuerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IssuerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(issuer.Table, issuer.Columns, sqlgraph.NewFieldSpec(issuer.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuer.FieldID)
		for i := range fields {
			if fields[i] != issuer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IssuerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(issuer.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = issuer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssuerGroupBy is the group-by builder for Issuer entities.
type IssuerGroupBy struct {
	selector
	build *IssuerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IssuerGroupBy) Aggregate(fns ...AggregateFunc) *IssuerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IssuerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerQuery, *IssuerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IssuerGroupBy) sqlScan(ctx context.Context, root *IssuerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IssuerSelect is the builder for selecting fields of Issuer entities.
type IssuerSelect struct {
	*IssuerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IssuerSelect) Aggregate(fns ...AggregateFunc) *IssuerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IssuerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerQuery, *IssuerSelect](ctx, _s.IssuerQuery, _s, _s.inters, v)
}

func (_s *IssuerSelect) sqlScan(ctx context.Context, root *IssuerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
