// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/issuer"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/revocation"
)

// License is the model entity for the License schema.
type License struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// LicenseUUID holds the value of the "license_uuid" field.
	LicenseUUID string `json:"license_uuid,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// IssuerName holds the value of the "issuer_name" field.
	IssuerName string `json:"issuer_name,omitempty"`
	// Audience holds the value of the "audience" field.
	Audience []string `json:"audience,omitempty"`
	// Features holds the value of the "features" field.
	Features []string `json:"features,omitempty"`
	// NotBefore holds the value of the "not_before" field.
	NotBefore time.Time `json:"not_before,omitempty"`
	// NotAfter holds the value of the "not_after" field.
	NotAfter time.Time `json:"not_after,omitempty"`
	// BindingsMeta holds the value of the "bindings_meta" field.
	BindingsMeta map[string]interface{} `json:"bindings_meta,omitempty"`
	// PayloadKind holds the value of the "payload_kind" field.
	PayloadKind license.PayloadKind `json:"payload_kind,omitempty"`
	// IdentitySha256 holds the value of the "identity_sha256" field.
	IdentitySha256 string `json:"identity_sha256,omitempty"`
	// BinarySha256 holds the value of the "binary_sha256" field.
	BinarySha256 string `json:"binary_sha256,omitempty"`
	// Pem holds the value of the "pem" field.
	Pem []byte `json:"pem,omitempty"`
	// Status holds the value of the "status" field.
	Status license.Status `json:"status,omitempty"`
	// ReplacesLicenseID holds the value of the "replaces_license_id" field.
	ReplacesLicenseID *uuid.UUID `json:"replaces_license_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LicenseQuery when eager-loading is set.
	Edges           LicenseEdges `json:"edges"`
	issuer_licenses *uuid.UUID
	selectValues    sql.SelectValues
}

// LicenseEdges holds the relations/edges for other nodes in the graph.
type LicenseEdges struct {
	// Issuer holds the value of the issuer edge.
	Issuer *Issuer `json:"issuer,omitempty"`
	// Totps holds the value of the totps edge.
	Totps []*TOTPSecret `json:"totps,omitempty"`
	// Revocation holds the value of the revocation edge.
	Revocation *Revocation `json:"revocation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// IssuerOrErr returns the Issuer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LicenseEdges) IssuerOrErr() (*Issuer, error) {
	if e.Issuer != nil {
		return e.Issuer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: issuer.Label}
	}
	return nil, &NotLoadedError{edge: "issuer"}
}

// TotpsOrErr returns the Totps value or an error if the edge
// was not loaded in eager-loading.
func (e LicenseEdges) TotpsOrErr() ([]*TOTPSecret, error) {
	if e.loadedTypes[1] {
		return e.Totps, nil
	}
	return nil, &NotLoadedError{edge: "totps"}
}

// RevocationOrErr returns the Revocation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LicenseEdges) RevocationOrErr() (*Revocation, error) {
	if e.Revocation != nil {
		return e.Revocation, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: revocation.Label}
	}
	return nil, &NotLoadedError{edge: "revocation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*License) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case license.FieldReplacesLicenseID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case license.FieldAudience, license.FieldFeatures, license.FieldBindingsMeta, license.FieldPem:
			values[i] = new([]byte)
		case license.FieldLicenseUUID, license.FieldSubject, license.FieldIssuerName, license.FieldPayloadKind, license.FieldIdentitySha256, license.FieldBinarySha256, license.FieldStatus:
			values[i] = new(sql.NullString)
		case license.FieldNotBefore, license.FieldNotAfter, license.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case license.FieldID:
			values[i] = new(uuid.UUID)
		case license.ForeignKeys[0]: // issuer_licenses
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the License fields.
func (_m *License) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case license.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case license.FieldLicenseUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license_uuid", values[i])
			} else if value.Valid {
				_m.LicenseUUID = value.String
			}
		case license.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case license.FieldIssuerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer_name", values[i])
			} else if value.Valid {
				_m.IssuerName = value.String
			}
		case license.FieldAudience:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field audience", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Audience); err != nil {
					return fmt.Errorf("unmarshal field audience: %w", err)
				}
			}
		case license.FieldFeatures:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field features", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Features); err != nil {
					return fmt.Errorf("unmarshal field features: %w", err)
				}
			}
		case license.FieldNotBefore:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_before", values[i])
			} else if value.Valid {
				_m.NotBefore = value.Time
			}
		case license.FieldNotAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_after", values[i])
			} else if value.Valid {
				_m.NotAfter = value.Time
			}
		case license.FieldBindingsMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bindings_meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BindingsMeta); err != nil {
					return fmt.Errorf("unmarshal field bindings_meta: %w", err)
				}
			}
		case license.FieldPayloadKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_kind", values[i])
			} else if value.Valid {
				_m.PayloadKind = license.PayloadKind(value.String)
			}
		case license.FieldIdentitySha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_sha256", values[i])
			} else if value.Valid {
				_m.IdentitySha256 = value.String
			}
		case license.FieldBinarySha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binary_sha256", values[i])
			} else if value.Valid {
				_m.BinarySha256 = value.String
			}
		case license.FieldPem:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pem", values[i])
			} else if value != nil {
				_m.Pem = *value
			}
		case license.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = license.Status(value.String)
			}
		case license.FieldReplacesLicenseID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field replaces_license_id", values[i])
			} else if value.Valid {
				_m.ReplacesLicenseID = new(uuid.UUID)
				*_m.ReplacesLicenseID = *value.S.(*uuid.UUID)
			}
		case license.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case license.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field issuer_licenses", values[i])
			} else if value.Valid {
				_m.issuer_licenses = new(uuid.UUID)
				*_m.issuer_licenses = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the License.
// This includes values selected through modifiers, order, etc.
func (_m *License) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIssuer queries the "issuer" edge of the License entity.
func (_m *License) QueryIssuer() *IssuerQuery {
	return NewLicenseClient(_m.config).QueryIssuer(_m)
}

// QueryTotps queries the "totps" edge of the License entity.
func (_m *License) QueryTotps() *TOTPSecretQuery {
	return NewLicenseClient(_m.config).QueryTotps(_m)
}

// QueryRevocation queries the "revocation" edge of the License entity.
func (_m *License) QueryRevocation() *RevocationQuery {
	return NewLicenseClient(_m.config).QueryRevocation(_m)
}

// Update returns a builder for updating this License.
// Note that you need to call License.Unwrap() before calling this method if this License
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *License) Update() *LicenseUpdateOne {
	return NewLicenseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the License entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *License) Unwrap() *License {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: License is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *License) String() string {
	var builder strings.Builder
	builder.WriteString("License(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("license_uuid=")
	builder.WriteString(_m.LicenseUUID)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("issuer_name=")
	builder.WriteString(_m.IssuerName)
	builder.WriteString(", ")
	builder.WriteString("audience=")
	builder.WriteString(fmt.Sprintf("%v", _m.Audience))
	builder.WriteString(", ")
	builder.WriteString("features=")
	builder.WriteString(fmt.Sprintf("%v", _m.Features))
	builder.WriteString(", ")
	builder.WriteString("not_before=")
	builder.WriteString(_m.NotBefore.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("not_after=")
	builder.WriteString(_m.NotAfter.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("bindings_meta=")
	builder.WriteString(fmt.Sprintf("%v", _m.BindingsMeta))
	builder.WriteString(", ")
	builder.WriteString("payload_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadKind))
	builder.WriteString(", ")
	builder.WriteString("identity_sha256=")
	builder.WriteString(_m.IdentitySha256)
	builder.WriteString(", ")
	builder.WriteString("binary_sha256=")
	builder.WriteString(_m.BinarySha256)
	builder.WriteString(", ")
	builder.WriteString("pem=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pem))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ReplacesLicenseID; v != nil {
		builder.WriteString("replaces_license_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Licenses is a parsable slice of License.
type Licenses []*License
