// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/oioio-space/maldev/internal/manager/store/ent/probetoken"
)

// ProbeToken is the model entity for the ProbeToken schema.
type ProbeToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// RemoteAddr holds the value of the "remote_addr" field.
	RemoteAddr string `json:"remote_addr,omitempty"`
	// Hostname holds the value of the "hostname" field.
	Hostname string `json:"hostname,omitempty"`
	// Os holds the value of the "os" field.
	Os string `json:"os,omitempty"`
	// Arch holds the value of the "arch" field.
	Arch string `json:"arch,omitempty"`
	// CPUBrand holds the value of the "cpu_brand" field.
	CPUBrand string `json:"cpu_brand,omitempty"`
	// LocalHex holds the value of the "local_hex" field.
	LocalHex string `json:"local_hex,omitempty"`
	// CompositeHex holds the value of the "composite_hex" field.
	CompositeHex string `json:"composite_hex,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProbeToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case probetoken.FieldID, probetoken.FieldLabel, probetoken.FieldRemoteAddr, probetoken.FieldHostname, probetoken.FieldOs, probetoken.FieldArch, probetoken.FieldCPUBrand, probetoken.FieldLocalHex, probetoken.FieldCompositeHex:
			values[i] = new(sql.NullString)
		case probetoken.FieldCreatedAt, probetoken.FieldExpiresAt, probetoken.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProbeToken fields.
func (_m *ProbeToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case probetoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case probetoken.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case probetoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case probetoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case probetoken.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		case probetoken.FieldRemoteAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_addr", values[i])
			} else if value.Valid {
				_m.RemoteAddr = value.String
			}
		case probetoken.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				_m.Hostname = value.String
			}
		case probetoken.FieldOs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value.Valid {
				_m.Os = value.String
			}
		case probetoken.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				_m.Arch = value.String
			}
		case probetoken.FieldCPUBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cpu_brand", values[i])
			} else if value.Valid {
				_m.CPUBrand = value.String
			}
		case probetoken.FieldLocalHex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_hex", values[i])
			} else if value.Valid {
				_m.LocalHex = value.String
			}
		case probetoken.FieldCompositeHex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field composite_hex", values[i])
			} else if value.Valid {
				_m.CompositeHex = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProbeToken.
// This includes values selected through modifiers, order, etc.
func (_m *ProbeToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProbeToken.
// Note that you need to call ProbeToken.Unwrap() before calling this method if this ProbeToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProbeToken) Update() *ProbeTokenUpdateOne {
	return NewProbeTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProbeToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProbeToken) Unwrap() *ProbeToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProbeToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProbeToken) String() string {
	var builder strings.Builder
	builder.WriteString("ProbeToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("remote_addr=")
	builder.WriteString(_m.RemoteAddr)
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(_m.Hostname)
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(_m.Os)
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(_m.Arch)
	builder.WriteString(", ")
	builder.WriteString("cpu_brand=")
	builder.WriteString(_m.CPUBrand)
	builder.WriteString(", ")
	builder.WriteString("local_hex=")
	builder.WriteString(_m.LocalHex)
	builder.WriteString(", ")
	builder.WriteString("composite_hex=")
	builder.WriteString(_m.CompositeHex)
	builder.WriteByte(')')
	return builder.String()
}

// ProbeTokens is a parsable slice of ProbeToken.
type ProbeTokens []*ProbeToken
