// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/recipientkey"
)

// RecipientKey is the model entity for the RecipientKey schema.
type RecipientKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// EncryptedPriv holds the value of the "encrypted_priv" field.
	EncryptedPriv []byte `json:"encrypted_priv,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecipientKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recipientkey.FieldPublicKey, recipientkey.FieldEncryptedPriv:
			values[i] = new([]byte)
		case recipientkey.FieldName:
			values[i] = new(sql.NullString)
		case recipientkey.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case recipientkey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecipientKey fields.
func (_m *RecipientKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recipientkey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case recipientkey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case recipientkey.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case recipientkey.FieldEncryptedPriv:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_priv", values[i])
			} else if value != nil {
				_m.EncryptedPriv = *value
			}
		case recipientkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecipientKey.
// This includes values selected through modifiers, order, etc.
func (_m *RecipientKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RecipientKey.
// Note that you need to call RecipientKey.Unwrap() before calling this method if this RecipientKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecipientKey) Update() *RecipientKeyUpdateOne {
	return NewRecipientKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecipientKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecipientKey) Unwrap() *RecipientKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecipientKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecipientKey) String() string {
	var builder strings.Builder
	builder.WriteString("RecipientKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("encrypted_priv=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedPriv))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RecipientKeys is a parsable slice of RecipientKey.
type RecipientKeys []*RecipientKey
