// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/recipientkey"
)

// RecipientKeyCreate is the builder for creating a RecipientKey entity.
type RecipientKeyCreate struct {
	config
	mutation *RecipientKeyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RecipientKeyCreate) SetName(v string) *RecipientKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *RecipientKeyCreate) SetPublicKey(v []byte) *RecipientKeyCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetEncryptedPriv sets the "encrypted_priv" field.
func (_c *RecipientKeyCreate) SetEncryptedPriv(v []byte) *RecipientKeyCreate {
	_c.mutation.SetEncryptedPriv(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RecipientKeyCreate) SetCreatedAt(v time.Time) *RecipientKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RecipientKeyCreate) SetNillableCreatedAt(v *time.Time) *RecipientKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RecipientKeyCreate) SetID(v uuid.UUID) *RecipientKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RecipientKeyCreate) SetNillableID(v *uuid.UUID) *RecipientKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RecipientKeyMutation object of the builder.
func (_c *RecipientKeyCreate) Mutation() *RecipientKeyMutation {
	return _c.mutation
}

// Save creates the RecipientKey in the database.
func (_c *RecipientKeyCreate) Save(ctx context.Context) (*RecipientKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RecipientKeyCreate) SaveX(ctx context.Context) *RecipientKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecipientKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecipientKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RecipientKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := recipientkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := recipientkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RecipientKeyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RecipientKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := recipientkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RecipientKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "RecipientKey.public_key"`)}
	}
	if v, ok := _c.mutation.PublicKey(); ok {
		if err := recipientkey.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "RecipientKey.public_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedPriv(); !ok {
		return &ValidationError{Name: "encrypted_priv", err: errors.New(`ent: missing required field "RecipientKey.encrypted_priv"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RecipientKey.created_at"`)}
	}
	return nil
}

func (_c *RecipientKeyCreate) sqlSave(ctx context.Context) (*RecipientKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RecipientKeyCreate) createSpec() (*RecipientKey, *sqlgraph.CreateSpec) {
	var (
		_node = &RecipientKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(recipientkey.Table, sqlgraph.NewFieldSpec(recipientkey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(recipientkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(recipientkey.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.EncryptedPriv(); ok {
		_spec.SetField(recipientkey.FieldEncryptedPriv, field.TypeBytes, value)
		_node.EncryptedPriv = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(recipientkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RecipientKeyCreateBulk is the builder for creating many RecipientKey entities in bulk.
type RecipientKeyCreateBulk struct {
	config
	err      error
	builders []*RecipientKeyCreate
}

// Save creates the RecipientKey entities in the database.
func (_c *RecipientKeyCreateBulk) Save(ctx context.Context) ([]*RecipientKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RecipientKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecipientKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RecipientKeyCreateBulk) SaveX(ctx context.Context) []*RecipientKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RecipientKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RecipientKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
