// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
	"github.com/oioio-space/maldev/internal/manager/store/ent/revocation"
)

// RevocationUpdate is the builder for updating Revocation entities.
type RevocationUpdate struct {
	config
	hooks    []Hook
	mutation *RevocationMutation
}

// Where appends a list predicates to the RevocationUpdate builder.
func (_u *RevocationUpdate) Where(ps ...predicate.Revocation) *RevocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReason sets the "reason" field.
func (_u *RevocationUpdate) SetReason(v string) *RevocationUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RevocationUpdate) SetNillableReason(v *string) *RevocationUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *RevocationUpdate) SetRevokedBy(v string) *RevocationUpdate {
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *RevocationUpdate) SetNillableRevokedBy(v *string) *RevocationUpdate {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// SetLicenseID sets the "license" edge to the License entity by ID.
func (_u *RevocationUpdate) SetLicenseID(id uuid.UUID) *RevocationUpdate {
	_u.mutation.SetLicenseID(id)
	return _u
}

// SetLicense sets the "license" edge to the License entity.
func (_u *RevocationUpdate) SetLicense(v *License) *RevocationUpdate {
	return _u.SetLicenseID(v.ID)
}

// Mutation returns the RevocationMutation object of the builder.
func (_u *RevocationUpdate) Mutation() *RevocationMutation {
	return _u.mutation
}

// ClearLicense clears the "license" edge to the License entity.
func (_u *RevocationUpdate) ClearLicense() *RevocationUpdate {
	_u.mutation.ClearLicense()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RevocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RevocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RevocationUpdate) check() error {
	if _u.mutation.LicenseCleared() && len(_u.mutation.LicenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Revocation.license"`)
	}
	return nil
}

func (_u *RevocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(revocation.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(revocation.FieldRevokedBy, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   revocation.LicenseTable,
			Columns: []string{revocation.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   revocation.LicenseTable,
			Columns: []string{revocation.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RevocationUpdateOne is the builder for updating a single Revocation entity.
type RevocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RevocationMutation
}

// SetReason sets the "reason" field.
func (_u *RevocationUpdateOne) SetReason(v string) *RevocationUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *RevocationUpdateOne) SetNillableReason(v *string) *RevocationUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *RevocationUpdateOne) SetRevokedBy(v string) *RevocationUpdateOne {
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *RevocationUpdateOne) SetNillableRevokedBy(v *string) *RevocationUpdateOne {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// SetLicenseID sets the "license" edge to the License entity by ID.
func (_u *RevocationUpdateOne) SetLicenseID(id uuid.UUID) *RevocationUpdateOne {
	_u.mutation.SetLicenseID(id)
	return _u
}

// SetLicense sets the "license" edge to the License entity.
func (_u *RevocationUpdateOne) SetLicense(v *License) *RevocationUpdateOne {
	return _u.SetLicenseID(v.ID)
}

// Mutation returns the RevocationMutation object of the builder.
func (_u *RevocationUpdateOne) Mutation() *RevocationMutation {
	return _u.mutation
}

// ClearLicense clears the "license" edge to the License entity.
func (_u *RevocationUpdateOne) ClearLicense() *RevocationUpdateOne {
	_u.mutation.ClearLicense()
	return _u
}

// Where appends a list predicates to the RevocationUpdate builder.
func (_u *RevocationUpdateOne) Where(ps ...predicate.Revocation) *RevocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RevocationUpdateOne) Select(field string, fields ...string) *RevocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Revocation entity.
func (_u *RevocationUpdateOne) Save(ctx context.Context) (*Revocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevocationUpdateOne) SaveX(ctx context.Context) *Revocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RevocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RevocationUpdateOne) check() error {
	if _u.mutation.LicenseCleared() && len(_u.mutation.LicenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Revocation.license"`)
	}
	return nil
}

func (_u *RevocationUpdateOne) sqlSave(ctx context.Context) (_node *Revocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Revocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, revocation.FieldID)
		for _, f := range fields {
			if !revocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != revocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(revocation.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(revocation.FieldRevokedBy, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   revocation.LicenseTable,
			Columns: []string{revocation.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   revocation.LicenseTable,
			Columns: []string{revocation.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Revocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
