// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/revocation"
)

// Revocation is the model entity for the Revocation schema.
type Revocation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt time.Time `json:"revoked_at,omitempty"`
	// RevokedBy holds the value of the "revoked_by" field.
	RevokedBy string `json:"revoked_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RevocationQuery when eager-loading is set.
	Edges              RevocationEdges `json:"edges"`
	license_revocation *uuid.UUID
	selectValues       sql.SelectValues
}

// RevocationEdges holds the relations/edges for other nodes in the graph.
type RevocationEdges struct {
	// License holds the value of the license edge.
	License *License `json:"license,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LicenseOrErr returns the License value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RevocationEdges) LicenseOrErr() (*License, error) {
	if e.License != nil {
		return e.License, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: license.Label}
	}
	return nil, &NotLoadedError{edge: "license"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Revocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case revocation.FieldReason, revocation.FieldRevokedBy:
			values[i] = new(sql.NullString)
		case revocation.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case revocation.FieldID:
			values[i] = new(uuid.UUID)
		case revocation.ForeignKeys[0]: // license_revocation
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Revocation fields.
func (_m *Revocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case revocation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case revocation.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case revocation.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = value.Time
			}
		case revocation.FieldRevokedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_by", values[i])
			} else if value.Valid {
				_m.RevokedBy = value.String
			}
		case revocation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field license_revocation", values[i])
			} else if value.Valid {
				_m.license_revocation = new(uuid.UUID)
				*_m.license_revocation = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Revocation.
// This includes values selected through modifiers, order, etc.
func (_m *Revocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLicense queries the "license" edge of the Revocation entity.
func (_m *Revocation) QueryLicense() *LicenseQuery {
	return NewRevocationClient(_m.config).QueryLicense(_m)
}

// Update returns a builder for updating this Revocation.
// Note that you need to call Revocation.Unwrap() before calling this method if this Revocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Revocation) Update() *RevocationUpdateOne {
	return NewRevocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Revocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Revocation) Unwrap() *Revocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Revocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Revocation) String() string {
	var builder strings.Builder
	builder.WriteString("Revocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("revoked_at=")
	builder.WriteString(_m.RevokedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("revoked_by=")
	builder.WriteString(_m.RevokedBy)
	builder.WriteByte(')')
	return builder.String()
}

// Revocations is a parsable slice of Revocation.
type Revocations []*Revocation
