// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oioio-space/maldev/internal/manager/store/ent/serverconfig"
)

// ServerConfigCreate is the builder for creating a ServerConfig entity.
type ServerConfigCreate struct {
	config
	mutation *ServerConfigMutation
	hooks    []Hook
}

// SetRevocationListen sets the "revocation_listen" field.
func (_c *ServerConfigCreate) SetRevocationListen(v string) *ServerConfigCreate {
	_c.mutation.SetRevocationListen(v)
	return _c
}

// SetNillableRevocationListen sets the "revocation_listen" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableRevocationListen(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetRevocationListen(*v)
	}
	return _c
}

// SetRevocationTLSCert sets the "revocation_tls_cert" field.
func (_c *ServerConfigCreate) SetRevocationTLSCert(v string) *ServerConfigCreate {
	_c.mutation.SetRevocationTLSCert(v)
	return _c
}

// SetNillableRevocationTLSCert sets the "revocation_tls_cert" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableRevocationTLSCert(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetRevocationTLSCert(*v)
	}
	return _c
}

// SetRevocationTLSKey sets the "revocation_tls_key" field.
func (_c *ServerConfigCreate) SetRevocationTLSKey(v string) *ServerConfigCreate {
	_c.mutation.SetRevocationTLSKey(v)
	return _c
}

// SetNillableRevocationTLSKey sets the "revocation_tls_key" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableRevocationTLSKey(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetRevocationTLSKey(*v)
	}
	return _c
}

// SetRevocationAdminTokenEnc sets the "revocation_admin_token_enc" field.
func (_c *ServerConfigCreate) SetRevocationAdminTokenEnc(v []byte) *ServerConfigCreate {
	_c.mutation.SetRevocationAdminTokenEnc(v)
	return _c
}

// SetRevocationPath sets the "revocation_path" field.
func (_c *ServerConfigCreate) SetRevocationPath(v string) *ServerConfigCreate {
	_c.mutation.SetRevocationPath(v)
	return _c
}

// SetNillableRevocationPath sets the "revocation_path" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableRevocationPath(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetRevocationPath(*v)
	}
	return _c
}

// SetHeartbeatListen sets the "heartbeat_listen" field.
func (_c *ServerConfigCreate) SetHeartbeatListen(v string) *ServerConfigCreate {
	_c.mutation.SetHeartbeatListen(v)
	return _c
}

// SetNillableHeartbeatListen sets the "heartbeat_listen" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableHeartbeatListen(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetHeartbeatListen(*v)
	}
	return _c
}

// SetHeartbeatTLSCert sets the "heartbeat_tls_cert" field.
func (_c *ServerConfigCreate) SetHeartbeatTLSCert(v string) *ServerConfigCreate {
	_c.mutation.SetHeartbeatTLSCert(v)
	return _c
}

// SetNillableHeartbeatTLSCert sets the "heartbeat_tls_cert" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableHeartbeatTLSCert(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetHeartbeatTLSCert(*v)
	}
	return _c
}

// SetHeartbeatTLSKey sets the "heartbeat_tls_key" field.
func (_c *ServerConfigCreate) SetHeartbeatTLSKey(v string) *ServerConfigCreate {
	_c.mutation.SetHeartbeatTLSKey(v)
	return _c
}

// SetNillableHeartbeatTLSKey sets the "heartbeat_tls_key" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableHeartbeatTLSKey(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetHeartbeatTLSKey(*v)
	}
	return _c
}

// SetHeartbeatPath sets the "heartbeat_path" field.
func (_c *ServerConfigCreate) SetHeartbeatPath(v string) *ServerConfigCreate {
	_c.mutation.SetHeartbeatPath(v)
	return _c
}

// SetNillableHeartbeatPath sets the "heartbeat_path" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableHeartbeatPath(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetHeartbeatPath(*v)
	}
	return _c
}

// SetProbeListen sets the "probe_listen" field.
func (_c *ServerConfigCreate) SetProbeListen(v string) *ServerConfigCreate {
	_c.mutation.SetProbeListen(v)
	return _c
}

// SetNillableProbeListen sets the "probe_listen" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableProbeListen(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetProbeListen(*v)
	}
	return _c
}

// SetProbeTLSCert sets the "probe_tls_cert" field.
func (_c *ServerConfigCreate) SetProbeTLSCert(v string) *ServerConfigCreate {
	_c.mutation.SetProbeTLSCert(v)
	return _c
}

// SetNillableProbeTLSCert sets the "probe_tls_cert" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableProbeTLSCert(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetProbeTLSCert(*v)
	}
	return _c
}

// SetProbeTLSKey sets the "probe_tls_key" field.
func (_c *ServerConfigCreate) SetProbeTLSKey(v string) *ServerConfigCreate {
	_c.mutation.SetProbeTLSKey(v)
	return _c
}

// SetNillableProbeTLSKey sets the "probe_tls_key" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableProbeTLSKey(v *string) *ServerConfigCreate {
	if v != nil {
		_c.SetProbeTLSKey(*v)
	}
	return _c
}

// SetProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field.
func (_c *ServerConfigCreate) SetProbeDefaultTTLSeconds(v int) *ServerConfigCreate {
	_c.mutation.SetProbeDefaultTTLSeconds(v)
	return _c
}

// SetNillableProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field if the given value is not nil.
func (_c *ServerConfigCreate) SetNillableProbeDefaultTTLSeconds(v *int) *ServerConfigCreate {
	if v != nil {
		_c.SetProbeDefaultTTLSeconds(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ServerConfigCreate) SetID(v int) *ServerConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ServerConfigMutation object of the builder.
func (_c *ServerConfigCreate) Mutation() *ServerConfigMutation {
	return _c.mutation
}

// Save creates the ServerConfig in the database.
func (_c *ServerConfigCreate) Save(ctx context.Context) (*ServerConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServerConfigCreate) SaveX(ctx context.Context) *ServerConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServerConfigCreate) defaults() {
	if _, ok := _c.mutation.RevocationListen(); !ok {
		v := serverconfig.DefaultRevocationListen
		_c.mutation.SetRevocationListen(v)
	}
	if _, ok := _c.mutation.RevocationPath(); !ok {
		v := serverconfig.DefaultRevocationPath
		_c.mutation.SetRevocationPath(v)
	}
	if _, ok := _c.mutation.HeartbeatListen(); !ok {
		v := serverconfig.DefaultHeartbeatListen
		_c.mutation.SetHeartbeatListen(v)
	}
	if _, ok := _c.mutation.HeartbeatPath(); !ok {
		v := serverconfig.DefaultHeartbeatPath
		_c.mutation.SetHeartbeatPath(v)
	}
	if _, ok := _c.mutation.ProbeListen(); !ok {
		v := serverconfig.DefaultProbeListen
		_c.mutation.SetProbeListen(v)
	}
	if _, ok := _c.mutation.ProbeDefaultTTLSeconds(); !ok {
		v := serverconfig.DefaultProbeDefaultTTLSeconds
		_c.mutation.SetProbeDefaultTTLSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServerConfigCreate) check() error {
	if _, ok := _c.mutation.RevocationListen(); !ok {
		return &ValidationError{Name: "revocation_listen", err: errors.New(`ent: missing required field "ServerConfig.revocation_listen"`)}
	}
	if _, ok := _c.mutation.RevocationPath(); !ok {
		return &ValidationError{Name: "revocation_path", err: errors.New(`ent: missing required field "ServerConfig.revocation_path"`)}
	}
	if _, ok := _c.mutation.HeartbeatListen(); !ok {
		return &ValidationError{Name: "heartbeat_listen", err: errors.New(`ent: missing required field "ServerConfig.heartbeat_listen"`)}
	}
	if _, ok := _c.mutation.HeartbeatPath(); !ok {
		return &ValidationError{Name: "heartbeat_path", err: errors.New(`ent: missing required field "ServerConfig.heartbeat_path"`)}
	}
	if _, ok := _c.mutation.ProbeListen(); !ok {
		return &ValidationError{Name: "probe_listen", err: errors.New(`ent: missing required field "ServerConfig.probe_listen"`)}
	}
	if _, ok := _c.mutation.ProbeDefaultTTLSeconds(); !ok {
		return &ValidationError{Name: "probe_default_ttl_seconds", err: errors.New(`ent: missing required field "ServerConfig.probe_default_ttl_seconds"`)}
	}
	return nil
}

func (_c *ServerConfigCreate) sqlSave(ctx context.Context) (*ServerConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServerConfigCreate) createSpec() (*ServerConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ServerConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(serverconfig.Table, sqlgraph.NewFieldSpec(serverconfig.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RevocationListen(); ok {
		_spec.SetField(serverconfig.FieldRevocationListen, field.TypeString, value)
		_node.RevocationListen = value
	}
	if value, ok := _c.mutation.RevocationTLSCert(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSCert, field.TypeString, value)
		_node.RevocationTLSCert = value
	}
	if value, ok := _c.mutation.RevocationTLSKey(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSKey, field.TypeString, value)
		_node.RevocationTLSKey = value
	}
	if value, ok := _c.mutation.RevocationAdminTokenEnc(); ok {
		_spec.SetField(serverconfig.FieldRevocationAdminTokenEnc, field.TypeBytes, value)
		_node.RevocationAdminTokenEnc = value
	}
	if value, ok := _c.mutation.RevocationPath(); ok {
		_spec.SetField(serverconfig.FieldRevocationPath, field.TypeString, value)
		_node.RevocationPath = value
	}
	if value, ok := _c.mutation.HeartbeatListen(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatListen, field.TypeString, value)
		_node.HeartbeatListen = value
	}
	if value, ok := _c.mutation.HeartbeatTLSCert(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSCert, field.TypeString, value)
		_node.HeartbeatTLSCert = value
	}
	if value, ok := _c.mutation.HeartbeatTLSKey(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSKey, field.TypeString, value)
		_node.HeartbeatTLSKey = value
	}
	if value, ok := _c.mutation.HeartbeatPath(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatPath, field.TypeString, value)
		_node.HeartbeatPath = value
	}
	if value, ok := _c.mutation.ProbeListen(); ok {
		_spec.SetField(serverconfig.FieldProbeListen, field.TypeString, value)
		_node.ProbeListen = value
	}
	if value, ok := _c.mutation.ProbeTLSCert(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSCert, field.TypeString, value)
		_node.ProbeTLSCert = value
	}
	if value, ok := _c.mutation.ProbeTLSKey(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSKey, field.TypeString, value)
		_node.ProbeTLSKey = value
	}
	if value, ok := _c.mutation.ProbeDefaultTTLSeconds(); ok {
		_spec.SetField(serverconfig.FieldProbeDefaultTTLSeconds, field.TypeInt, value)
		_node.ProbeDefaultTTLSeconds = value
	}
	return _node, _spec
}

// ServerConfigCreateBulk is the builder for creating many ServerConfig entities in bulk.
type ServerConfigCreateBulk struct {
	config
	err      error
	builders []*ServerConfigCreate
}

// Save creates the ServerConfig entities in the database.
func (_c *ServerConfigCreateBulk) Save(ctx context.Context) ([]*ServerConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServerConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServerConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServerConfigCreateBulk) SaveX(ctx context.Context) []*ServerConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServerConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServerConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
