// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
	"github.com/oioio-space/maldev/internal/manager/store/ent/serverconfig"
)

// ServerConfigUpdate is the builder for updating ServerConfig entities.
type ServerConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ServerConfigMutation
}

// Where appends a list predicates to the ServerConfigUpdate builder.
func (_u *ServerConfigUpdate) Where(ps ...predicate.ServerConfig) *ServerConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRevocationListen sets the "revocation_listen" field.
func (_u *ServerConfigUpdate) SetRevocationListen(v string) *ServerConfigUpdate {
	_u.mutation.SetRevocationListen(v)
	return _u
}

// SetNillableRevocationListen sets the "revocation_listen" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableRevocationListen(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetRevocationListen(*v)
	}
	return _u
}

// SetRevocationTLSCert sets the "revocation_tls_cert" field.
func (_u *ServerConfigUpdate) SetRevocationTLSCert(v string) *ServerConfigUpdate {
	_u.mutation.SetRevocationTLSCert(v)
	return _u
}

// SetNillableRevocationTLSCert sets the "revocation_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableRevocationTLSCert(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetRevocationTLSCert(*v)
	}
	return _u
}

// ClearRevocationTLSCert clears the value of the "revocation_tls_cert" field.
func (_u *ServerConfigUpdate) ClearRevocationTLSCert() *ServerConfigUpdate {
	_u.mutation.ClearRevocationTLSCert()
	return _u
}

// SetRevocationTLSKey sets the "revocation_tls_key" field.
func (_u *ServerConfigUpdate) SetRevocationTLSKey(v string) *ServerConfigUpdate {
	_u.mutation.SetRevocationTLSKey(v)
	return _u
}

// SetNillableRevocationTLSKey sets the "revocation_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableRevocationTLSKey(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetRevocationTLSKey(*v)
	}
	return _u
}

// ClearRevocationTLSKey clears the value of the "revocation_tls_key" field.
func (_u *ServerConfigUpdate) ClearRevocationTLSKey() *ServerConfigUpdate {
	_u.mutation.ClearRevocationTLSKey()
	return _u
}

// SetRevocationAdminTokenEnc sets the "revocation_admin_token_enc" field.
func (_u *ServerConfigUpdate) SetRevocationAdminTokenEnc(v []byte) *ServerConfigUpdate {
	_u.mutation.SetRevocationAdminTokenEnc(v)
	return _u
}

// ClearRevocationAdminTokenEnc clears the value of the "revocation_admin_token_enc" field.
func (_u *ServerConfigUpdate) ClearRevocationAdminTokenEnc() *ServerConfigUpdate {
	_u.mutation.ClearRevocationAdminTokenEnc()
	return _u
}

// SetRevocationPath sets the "revocation_path" field.
func (_u *ServerConfigUpdate) SetRevocationPath(v string) *ServerConfigUpdate {
	_u.mutation.SetRevocationPath(v)
	return _u
}

// SetNillableRevocationPath sets the "revocation_path" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableRevocationPath(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetRevocationPath(*v)
	}
	return _u
}

// SetHeartbeatListen sets the "heartbeat_listen" field.
func (_u *ServerConfigUpdate) SetHeartbeatListen(v string) *ServerConfigUpdate {
	_u.mutation.SetHeartbeatListen(v)
	return _u
}

// SetNillableHeartbeatListen sets the "heartbeat_listen" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableHeartbeatListen(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetHeartbeatListen(*v)
	}
	return _u
}

// SetHeartbeatTLSCert sets the "heartbeat_tls_cert" field.
func (_u *ServerConfigUpdate) SetHeartbeatTLSCert(v string) *ServerConfigUpdate {
	_u.mutation.SetHeartbeatTLSCert(v)
	return _u
}

// SetNillableHeartbeatTLSCert sets the "heartbeat_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableHeartbeatTLSCert(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetHeartbeatTLSCert(*v)
	}
	return _u
}

// ClearHeartbeatTLSCert clears the value of the "heartbeat_tls_cert" field.
func (_u *ServerConfigUpdate) ClearHeartbeatTLSCert() *ServerConfigUpdate {
	_u.mutation.ClearHeartbeatTLSCert()
	return _u
}

// SetHeartbeatTLSKey sets the "heartbeat_tls_key" field.
func (_u *ServerConfigUpdate) SetHeartbeatTLSKey(v string) *ServerConfigUpdate {
	_u.mutation.SetHeartbeatTLSKey(v)
	return _u
}

// SetNillableHeartbeatTLSKey sets the "heartbeat_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableHeartbeatTLSKey(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetHeartbeatTLSKey(*v)
	}
	return _u
}

// ClearHeartbeatTLSKey clears the value of the "heartbeat_tls_key" field.
func (_u *ServerConfigUpdate) ClearHeartbeatTLSKey() *ServerConfigUpdate {
	_u.mutation.ClearHeartbeatTLSKey()
	return _u
}

// SetHeartbeatPath sets the "heartbeat_path" field.
func (_u *ServerConfigUpdate) SetHeartbeatPath(v string) *ServerConfigUpdate {
	_u.mutation.SetHeartbeatPath(v)
	return _u
}

// SetNillableHeartbeatPath sets the "heartbeat_path" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableHeartbeatPath(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetHeartbeatPath(*v)
	}
	return _u
}

// SetProbeListen sets the "probe_listen" field.
func (_u *ServerConfigUpdate) SetProbeListen(v string) *ServerConfigUpdate {
	_u.mutation.SetProbeListen(v)
	return _u
}

// SetNillableProbeListen sets the "probe_listen" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableProbeListen(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetProbeListen(*v)
	}
	return _u
}

// SetProbeTLSCert sets the "probe_tls_cert" field.
func (_u *ServerConfigUpdate) SetProbeTLSCert(v string) *ServerConfigUpdate {
	_u.mutation.SetProbeTLSCert(v)
	return _u
}

// SetNillableProbeTLSCert sets the "probe_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableProbeTLSCert(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetProbeTLSCert(*v)
	}
	return _u
}

// ClearProbeTLSCert clears the value of the "probe_tls_cert" field.
func (_u *ServerConfigUpdate) ClearProbeTLSCert() *ServerConfigUpdate {
	_u.mutation.ClearProbeTLSCert()
	return _u
}

// SetProbeTLSKey sets the "probe_tls_key" field.
func (_u *ServerConfigUpdate) SetProbeTLSKey(v string) *ServerConfigUpdate {
	_u.mutation.SetProbeTLSKey(v)
	return _u
}

// SetNillableProbeTLSKey sets the "probe_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableProbeTLSKey(v *string) *ServerConfigUpdate {
	if v != nil {
		_u.SetProbeTLSKey(*v)
	}
	return _u
}

// ClearProbeTLSKey clears the value of the "probe_tls_key" field.
func (_u *ServerConfigUpdate) ClearProbeTLSKey() *ServerConfigUpdate {
	_u.mutation.ClearProbeTLSKey()
	return _u
}

// SetProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field.
func (_u *ServerConfigUpdate) SetProbeDefaultTTLSeconds(v int) *ServerConfigUpdate {
	_u.mutation.ResetProbeDefaultTTLSeconds()
	_u.mutation.SetProbeDefaultTTLSeconds(v)
	return _u
}

// SetNillableProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field if the given value is not nil.
func (_u *ServerConfigUpdate) SetNillableProbeDefaultTTLSeconds(v *int) *ServerConfigUpdate {
	if v != nil {
		_u.SetProbeDefaultTTLSeconds(*v)
	}
	return _u
}

// AddProbeDefaultTTLSeconds adds value to the "probe_default_ttl_seconds" field.
func (_u *ServerConfigUpdate) AddProbeDefaultTTLSeconds(v int) *ServerConfigUpdate {
	_u.mutation.AddProbeDefaultTTLSeconds(v)
	return _u
}

// Mutation returns the ServerConfigMutation object of the builder.
func (_u *ServerConfigUpdate) Mutation() *ServerConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServerConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServerConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServerConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverconfig.Table, serverconfig.Columns, sqlgraph.NewFieldSpec(serverconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RevocationListen(); ok {
		_spec.SetField(serverconfig.FieldRevocationListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevocationTLSCert(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSCert, field.TypeString, value)
	}
	if _u.mutation.RevocationTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldRevocationTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.RevocationTLSKey(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSKey, field.TypeString, value)
	}
	if _u.mutation.RevocationTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldRevocationTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.RevocationAdminTokenEnc(); ok {
		_spec.SetField(serverconfig.FieldRevocationAdminTokenEnc, field.TypeBytes, value)
	}
	if _u.mutation.RevocationAdminTokenEncCleared() {
		_spec.ClearField(serverconfig.FieldRevocationAdminTokenEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.RevocationPath(); ok {
		_spec.SetField(serverconfig.FieldRevocationPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatListen(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatTLSCert(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSCert, field.TypeString, value)
	}
	if _u.mutation.HeartbeatTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldHeartbeatTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatTLSKey(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSKey, field.TypeString, value)
	}
	if _u.mutation.HeartbeatTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldHeartbeatTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatPath(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeListen(); ok {
		_spec.SetField(serverconfig.FieldProbeListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeTLSCert(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSCert, field.TypeString, value)
	}
	if _u.mutation.ProbeTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldProbeTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.ProbeTLSKey(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSKey, field.TypeString, value)
	}
	if _u.mutation.ProbeTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldProbeTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.ProbeDefaultTTLSeconds(); ok {
		_spec.SetField(serverconfig.FieldProbeDefaultTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeDefaultTTLSeconds(); ok {
		_spec.AddField(serverconfig.FieldProbeDefaultTTLSeconds, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServerConfigUpdateOne is the builder for updating a single ServerConfig entity.
type ServerConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServerConfigMutation
}

// SetRevocationListen sets the "revocation_listen" field.
func (_u *ServerConfigUpdateOne) SetRevocationListen(v string) *ServerConfigUpdateOne {
	_u.mutation.SetRevocationListen(v)
	return _u
}

// SetNillableRevocationListen sets the "revocation_listen" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableRevocationListen(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetRevocationListen(*v)
	}
	return _u
}

// SetRevocationTLSCert sets the "revocation_tls_cert" field.
func (_u *ServerConfigUpdateOne) SetRevocationTLSCert(v string) *ServerConfigUpdateOne {
	_u.mutation.SetRevocationTLSCert(v)
	return _u
}

// SetNillableRevocationTLSCert sets the "revocation_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableRevocationTLSCert(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetRevocationTLSCert(*v)
	}
	return _u
}

// ClearRevocationTLSCert clears the value of the "revocation_tls_cert" field.
func (_u *ServerConfigUpdateOne) ClearRevocationTLSCert() *ServerConfigUpdateOne {
	_u.mutation.ClearRevocationTLSCert()
	return _u
}

// SetRevocationTLSKey sets the "revocation_tls_key" field.
func (_u *ServerConfigUpdateOne) SetRevocationTLSKey(v string) *ServerConfigUpdateOne {
	_u.mutation.SetRevocationTLSKey(v)
	return _u
}

// SetNillableRevocationTLSKey sets the "revocation_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableRevocationTLSKey(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetRevocationTLSKey(*v)
	}
	return _u
}

// ClearRevocationTLSKey clears the value of the "revocation_tls_key" field.
func (_u *ServerConfigUpdateOne) ClearRevocationTLSKey() *ServerConfigUpdateOne {
	_u.mutation.ClearRevocationTLSKey()
	return _u
}

// SetRevocationAdminTokenEnc sets the "revocation_admin_token_enc" field.
func (_u *ServerConfigUpdateOne) SetRevocationAdminTokenEnc(v []byte) *ServerConfigUpdateOne {
	_u.mutation.SetRevocationAdminTokenEnc(v)
	return _u
}

// ClearRevocationAdminTokenEnc clears the value of the "revocation_admin_token_enc" field.
func (_u *ServerConfigUpdateOne) ClearRevocationAdminTokenEnc() *ServerConfigUpdateOne {
	_u.mutation.ClearRevocationAdminTokenEnc()
	return _u
}

// SetRevocationPath sets the "revocation_path" field.
func (_u *ServerConfigUpdateOne) SetRevocationPath(v string) *ServerConfigUpdateOne {
	_u.mutation.SetRevocationPath(v)
	return _u
}

// SetNillableRevocationPath sets the "revocation_path" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableRevocationPath(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetRevocationPath(*v)
	}
	return _u
}

// SetHeartbeatListen sets the "heartbeat_listen" field.
func (_u *ServerConfigUpdateOne) SetHeartbeatListen(v string) *ServerConfigUpdateOne {
	_u.mutation.SetHeartbeatListen(v)
	return _u
}

// SetNillableHeartbeatListen sets the "heartbeat_listen" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableHeartbeatListen(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetHeartbeatListen(*v)
	}
	return _u
}

// SetHeartbeatTLSCert sets the "heartbeat_tls_cert" field.
func (_u *ServerConfigUpdateOne) SetHeartbeatTLSCert(v string) *ServerConfigUpdateOne {
	_u.mutation.SetHeartbeatTLSCert(v)
	return _u
}

// SetNillableHeartbeatTLSCert sets the "heartbeat_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableHeartbeatTLSCert(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetHeartbeatTLSCert(*v)
	}
	return _u
}

// ClearHeartbeatTLSCert clears the value of the "heartbeat_tls_cert" field.
func (_u *ServerConfigUpdateOne) ClearHeartbeatTLSCert() *ServerConfigUpdateOne {
	_u.mutation.ClearHeartbeatTLSCert()
	return _u
}

// SetHeartbeatTLSKey sets the "heartbeat_tls_key" field.
func (_u *ServerConfigUpdateOne) SetHeartbeatTLSKey(v string) *ServerConfigUpdateOne {
	_u.mutation.SetHeartbeatTLSKey(v)
	return _u
}

// SetNillableHeartbeatTLSKey sets the "heartbeat_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableHeartbeatTLSKey(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetHeartbeatTLSKey(*v)
	}
	return _u
}

// ClearHeartbeatTLSKey clears the value of the "heartbeat_tls_key" field.
func (_u *ServerConfigUpdateOne) ClearHeartbeatTLSKey() *ServerConfigUpdateOne {
	_u.mutation.ClearHeartbeatTLSKey()
	return _u
}

// SetHeartbeatPath sets the "heartbeat_path" field.
func (_u *ServerConfigUpdateOne) SetHeartbeatPath(v string) *ServerConfigUpdateOne {
	_u.mutation.SetHeartbeatPath(v)
	return _u
}

// SetNillableHeartbeatPath sets the "heartbeat_path" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableHeartbeatPath(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetHeartbeatPath(*v)
	}
	return _u
}

// SetProbeListen sets the "probe_listen" field.
func (_u *ServerConfigUpdateOne) SetProbeListen(v string) *ServerConfigUpdateOne {
	_u.mutation.SetProbeListen(v)
	return _u
}

// SetNillableProbeListen sets the "probe_listen" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableProbeListen(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetProbeListen(*v)
	}
	return _u
}

// SetProbeTLSCert sets the "probe_tls_cert" field.
func (_u *ServerConfigUpdateOne) SetProbeTLSCert(v string) *ServerConfigUpdateOne {
	_u.mutation.SetProbeTLSCert(v)
	return _u
}

// SetNillableProbeTLSCert sets the "probe_tls_cert" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableProbeTLSCert(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetProbeTLSCert(*v)
	}
	return _u
}

// ClearProbeTLSCert clears the value of the "probe_tls_cert" field.
func (_u *ServerConfigUpdateOne) ClearProbeTLSCert() *ServerConfigUpdateOne {
	_u.mutation.ClearProbeTLSCert()
	return _u
}

// SetProbeTLSKey sets the "probe_tls_key" field.
func (_u *ServerConfigUpdateOne) SetProbeTLSKey(v string) *ServerConfigUpdateOne {
	_u.mutation.SetProbeTLSKey(v)
	return _u
}

// SetNillableProbeTLSKey sets the "probe_tls_key" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableProbeTLSKey(v *string) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetProbeTLSKey(*v)
	}
	return _u
}

// ClearProbeTLSKey clears the value of the "probe_tls_key" field.
func (_u *ServerConfigUpdateOne) ClearProbeTLSKey() *ServerConfigUpdateOne {
	_u.mutation.ClearProbeTLSKey()
	return _u
}

// SetProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field.
func (_u *ServerConfigUpdateOne) SetProbeDefaultTTLSeconds(v int) *ServerConfigUpdateOne {
	_u.mutation.ResetProbeDefaultTTLSeconds()
	_u.mutation.SetProbeDefaultTTLSeconds(v)
	return _u
}

// SetNillableProbeDefaultTTLSeconds sets the "probe_default_ttl_seconds" field if the given value is not nil.
func (_u *ServerConfigUpdateOne) SetNillableProbeDefaultTTLSeconds(v *int) *ServerConfigUpdateOne {
	if v != nil {
		_u.SetProbeDefaultTTLSeconds(*v)
	}
	return _u
}

// AddProbeDefaultTTLSeconds adds value to the "probe_default_ttl_seconds" field.
func (_u *ServerConfigUpdateOne) AddProbeDefaultTTLSeconds(v int) *ServerConfigUpdateOne {
	_u.mutation.AddProbeDefaultTTLSeconds(v)
	return _u
}

// Mutation returns the ServerConfigMutation object of the builder.
func (_u *ServerConfigUpdateOne) Mutation() *ServerConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServerConfigUpdate builder.
func (_u *ServerConfigUpdateOne) Where(ps ...predicate.ServerConfig) *ServerConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServerConfigUpdateOne) Select(field string, fields ...string) *ServerConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServerConfig entity.
func (_u *ServerConfigUpdateOne) Save(ctx context.Context) (*ServerConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServerConfigUpdateOne) SaveX(ctx context.Context) *ServerConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServerConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServerConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServerConfigUpdateOne) sqlSave(ctx context.Context) (_node *ServerConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(serverconfig.Table, serverconfig.Columns, sqlgraph.NewFieldSpec(serverconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServerConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serverconfig.FieldID)
		for _, f := range fields {
			if !serverconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serverconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RevocationListen(); ok {
		_spec.SetField(serverconfig.FieldRevocationListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevocationTLSCert(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSCert, field.TypeString, value)
	}
	if _u.mutation.RevocationTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldRevocationTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.RevocationTLSKey(); ok {
		_spec.SetField(serverconfig.FieldRevocationTLSKey, field.TypeString, value)
	}
	if _u.mutation.RevocationTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldRevocationTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.RevocationAdminTokenEnc(); ok {
		_spec.SetField(serverconfig.FieldRevocationAdminTokenEnc, field.TypeBytes, value)
	}
	if _u.mutation.RevocationAdminTokenEncCleared() {
		_spec.ClearField(serverconfig.FieldRevocationAdminTokenEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.RevocationPath(); ok {
		_spec.SetField(serverconfig.FieldRevocationPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatListen(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatTLSCert(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSCert, field.TypeString, value)
	}
	if _u.mutation.HeartbeatTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldHeartbeatTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatTLSKey(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatTLSKey, field.TypeString, value)
	}
	if _u.mutation.HeartbeatTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldHeartbeatTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.HeartbeatPath(); ok {
		_spec.SetField(serverconfig.FieldHeartbeatPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeListen(); ok {
		_spec.SetField(serverconfig.FieldProbeListen, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbeTLSCert(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSCert, field.TypeString, value)
	}
	if _u.mutation.ProbeTLSCertCleared() {
		_spec.ClearField(serverconfig.FieldProbeTLSCert, field.TypeString)
	}
	if value, ok := _u.mutation.ProbeTLSKey(); ok {
		_spec.SetField(serverconfig.FieldProbeTLSKey, field.TypeString, value)
	}
	if _u.mutation.ProbeTLSKeyCleared() {
		_spec.ClearField(serverconfig.FieldProbeTLSKey, field.TypeString)
	}
	if value, ok := _u.mutation.ProbeDefaultTTLSeconds(); ok {
		_spec.SetField(serverconfig.FieldProbeDefaultTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeDefaultTTLSeconds(); ok {
		_spec.AddField(serverconfig.FieldProbeDefaultTTLSeconds, field.TypeInt, value)
	}
	_node = &ServerConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serverconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
