// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/oioio-space/maldev/internal/manager/store/ent/setting"
)

// Setting is the model entity for the Setting schema.
type Setting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DefaultIssuerName holds the value of the "default_issuer_name" field.
	DefaultIssuerName string `json:"default_issuer_name,omitempty"`
	// DefaultAudience holds the value of the "default_audience" field.
	DefaultAudience []string `json:"default_audience,omitempty"`
	// DefaultTTLSeconds holds the value of the "default_ttl_seconds" field.
	DefaultTTLSeconds int `json:"default_ttl_seconds,omitempty"`
	// DefaultArgonPreset holds the value of the "default_argon_preset" field.
	DefaultArgonPreset setting.DefaultArgonPreset `json:"default_argon_preset,omitempty"`
	// OperatorName holds the value of the "operator_name" field.
	OperatorName string `json:"operator_name,omitempty"`
	// AutoStartServers holds the value of the "auto_start_servers" field.
	AutoStartServers bool `json:"auto_start_servers,omitempty"`
	// ConfirmQuitWithServers holds the value of the "confirm_quit_with_servers" field.
	ConfirmQuitWithServers bool `json:"confirm_quit_with_servers,omitempty"`
	// Theme holds the value of the "theme" field.
	Theme setting.Theme `json:"theme,omitempty"`
	// KekSalt holds the value of the "kek_salt" field.
	KekSalt []byte `json:"kek_salt,omitempty"`
	// KekCanary holds the value of the "kek_canary" field.
	KekCanary    []byte `json:"kek_canary,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Setting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case setting.FieldDefaultAudience, setting.FieldKekSalt, setting.FieldKekCanary:
			values[i] = new([]byte)
		case setting.FieldAutoStartServers, setting.FieldConfirmQuitWithServers:
			values[i] = new(sql.NullBool)
		case setting.FieldID, setting.FieldDefaultTTLSeconds:
			values[i] = new(sql.NullInt64)
		case setting.FieldDefaultIssuerName, setting.FieldDefaultArgonPreset, setting.FieldOperatorName, setting.FieldTheme:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Setting fields.
func (_m *Setting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case setting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case setting.FieldDefaultIssuerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_issuer_name", values[i])
			} else if value.Valid {
				_m.DefaultIssuerName = value.String
			}
		case setting.FieldDefaultAudience:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field default_audience", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DefaultAudience); err != nil {
					return fmt.Errorf("unmarshal field default_audience: %w", err)
				}
			}
		case setting.FieldDefaultTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_ttl_seconds", values[i])
			} else if value.Valid {
				_m.DefaultTTLSeconds = int(value.Int64)
			}
		case setting.FieldDefaultArgonPreset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_argon_preset", values[i])
			} else if value.Valid {
				_m.DefaultArgonPreset = setting.DefaultArgonPreset(value.String)
			}
		case setting.FieldOperatorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator_name", values[i])
			} else if value.Valid {
				_m.OperatorName = value.String
			}
		case setting.FieldAutoStartServers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_start_servers", values[i])
			} else if value.Valid {
				_m.AutoStartServers = value.Bool
			}
		case setting.FieldConfirmQuitWithServers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field confirm_quit_with_servers", values[i])
			} else if value.Valid {
				_m.ConfirmQuitWithServers = value.Bool
			}
		case setting.FieldTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme", values[i])
			} else if value.Valid {
				_m.Theme = setting.Theme(value.String)
			}
		case setting.FieldKekSalt:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field kek_salt", values[i])
			} else if value != nil {
				_m.KekSalt = *value
			}
		case setting.FieldKekCanary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field kek_canary", values[i])
			} else if value != nil {
				_m.KekCanary = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Setting.
// This includes values selected through modifiers, order, etc.
func (_m *Setting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Setting.
// Note that you need to call Setting.Unwrap() before calling this method if this Setting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Setting) Update() *SettingUpdateOne {
	return NewSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Setting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Setting) Unwrap() *Setting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Setting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Setting) String() string {
	var builder strings.Builder
	builder.WriteString("Setting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("default_issuer_name=")
	builder.WriteString(_m.DefaultIssuerName)
	builder.WriteString(", ")
	builder.WriteString("default_audience=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultAudience))
	builder.WriteString(", ")
	builder.WriteString("default_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("default_argon_preset=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultArgonPreset))
	builder.WriteString(", ")
	builder.WriteString("operator_name=")
	builder.WriteString(_m.OperatorName)
	builder.WriteString(", ")
	builder.WriteString("auto_start_servers=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoStartServers))
	builder.WriteString(", ")
	builder.WriteString("confirm_quit_with_servers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfirmQuitWithServers))
	builder.WriteString(", ")
	builder.WriteString("theme=")
	builder.WriteString(fmt.Sprintf("%v", _m.Theme))
	builder.WriteString(", ")
	builder.WriteString("kek_salt=")
	builder.WriteString(fmt.Sprintf("%v", _m.KekSalt))
	builder.WriteString(", ")
	builder.WriteString("kek_canary=")
	builder.WriteString(fmt.Sprintf("%v", _m.KekCanary))
	builder.WriteByte(')')
	return builder.String()
}

// Settings is a parsable slice of Setting.
type Settings []*Setting
