// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/totpsecret"
)

// TOTPSecretCreate is the builder for creating a TOTPSecret entity.
type TOTPSecretCreate struct {
	config
	mutation *TOTPSecretMutation
	hooks    []Hook
}

// SetEncryptedSecret sets the "encrypted_secret" field.
func (_c *TOTPSecretCreate) SetEncryptedSecret(v []byte) *TOTPSecretCreate {
	_c.mutation.SetEncryptedSecret(v)
	return _c
}

// SetAccountLabel sets the "account_label" field.
func (_c *TOTPSecretCreate) SetAccountLabel(v string) *TOTPSecretCreate {
	_c.mutation.SetAccountLabel(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TOTPSecretCreate) SetCreatedAt(v time.Time) *TOTPSecretCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TOTPSecretCreate) SetNillableCreatedAt(v *time.Time) *TOTPSecretCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TOTPSecretCreate) SetID(v uuid.UUID) *TOTPSecretCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TOTPSecretCreate) SetNillableID(v *uuid.UUID) *TOTPSecretCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLicenseID sets the "license" edge to the License entity by ID.
func (_c *TOTPSecretCreate) SetLicenseID(id uuid.UUID) *TOTPSecretCreate {
	_c.mutation.SetLicenseID(id)
	return _c
}

// SetNillableLicenseID sets the "license" edge to the License entity by ID if the given value is not nil.
func (_c *TOTPSecretCreate) SetNillableLicenseID(id *uuid.UUID) *TOTPSecretCreate {
	if id != nil {
		_c = _c.SetLicenseID(*id)
	}
	return _c
}

// SetLicense sets the "license" edge to the License entity.
func (_c *TOTPSecretCreate) SetLicense(v *License) *TOTPSecretCreate {
	return _c.SetLicenseID(v.ID)
}

// Mutation returns the TOTPSecretMutation object of the builder.
func (_c *TOTPSecretCreate) Mutation() *TOTPSecretMutation {
	return _c.mutation
}

// Save creates the TOTPSecret in the database.
func (_c *TOTPSecretCreate) Save(ctx context.Context) (*TOTPSecret, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TOTPSecretCreate) SaveX(ctx context.Context) *TOTPSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TOTPSecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TOTPSecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TOTPSecretCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := totpsecret.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := totpsecret.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TOTPSecretCreate) check() error {
	if _, ok := _c.mutation.EncryptedSecret(); !ok {
		return &ValidationError{Name: "encrypted_secret", err: errors.New(`ent: missing required field "TOTPSecret.encrypted_secret"`)}
	}
	if _, ok := _c.mutation.AccountLabel(); !ok {
		return &ValidationError{Name: "account_label", err: errors.New(`ent: missing required field "TOTPSecret.account_label"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TOTPSecret.created_at"`)}
	}
	return nil
}

func (_c *TOTPSecretCreate) sqlSave(ctx context.Context) (*TOTPSecret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TOTPSecretCreate) createSpec() (*TOTPSecret, *sqlgraph.CreateSpec) {
	var (
		_node = &TOTPSecret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(totpsecret.Table, sqlgraph.NewFieldSpec(totpsecret.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EncryptedSecret(); ok {
		_spec.SetField(totpsecret.FieldEncryptedSecret, field.TypeBytes, value)
		_node.EncryptedSecret = value
	}
	if value, ok := _c.mutation.AccountLabel(); ok {
		_spec.SetField(totpsecret.FieldAccountLabel, field.TypeString, value)
		_node.AccountLabel = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(totpsecret.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.LicenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpsecret.LicenseTable,
			Columns: []string{totpsecret.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.license_totps = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TOTPSecretCreateBulk is the builder for creating many TOTPSecret entities in bulk.
type TOTPSecretCreateBulk struct {
	config
	err      error
	builders []*TOTPSecretCreate
}

// Save creates the TOTPSecret entities in the database.
func (_c *TOTPSecretCreateBulk) Save(ctx context.Context) ([]*TOTPSecret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TOTPSecret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TOTPSecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TOTPSecretCreateBulk) SaveX(ctx context.Context) []*TOTPSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TOTPSecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TOTPSecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
