// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/totpsecret"
)

// TOTPSecret is the model entity for the TOTPSecret schema.
type TOTPSecret struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EncryptedSecret holds the value of the "encrypted_secret" field.
	EncryptedSecret []byte `json:"encrypted_secret,omitempty"`
	// AccountLabel holds the value of the "account_label" field.
	AccountLabel string `json:"account_label,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TOTPSecretQuery when eager-loading is set.
	Edges         TOTPSecretEdges `json:"edges"`
	license_totps *uuid.UUID
	selectValues  sql.SelectValues
}

// TOTPSecretEdges holds the relations/edges for other nodes in the graph.
type TOTPSecretEdges struct {
	// License holds the value of the license edge.
	License *License `json:"license,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LicenseOrErr returns the License value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TOTPSecretEdges) LicenseOrErr() (*License, error) {
	if e.License != nil {
		return e.License, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: license.Label}
	}
	return nil, &NotLoadedError{edge: "license"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TOTPSecret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case totpsecret.FieldEncryptedSecret:
			values[i] = new([]byte)
		case totpsecret.FieldAccountLabel:
			values[i] = new(sql.NullString)
		case totpsecret.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case totpsecret.FieldID:
			values[i] = new(uuid.UUID)
		case totpsecret.ForeignKeys[0]: // license_totps
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TOTPSecret fields.
func (_m *TOTPSecret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case totpsecret.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case totpsecret.FieldEncryptedSecret:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_secret", values[i])
			} else if value != nil {
				_m.EncryptedSecret = *value
			}
		case totpsecret.FieldAccountLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_label", values[i])
			} else if value.Valid {
				_m.AccountLabel = value.String
			}
		case totpsecret.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case totpsecret.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field license_totps", values[i])
			} else if value.Valid {
				_m.license_totps = new(uuid.UUID)
				*_m.license_totps = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TOTPSecret.
// This includes values selected through modifiers, order, etc.
func (_m *TOTPSecret) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLicense queries the "license" edge of the TOTPSecret entity.
func (_m *TOTPSecret) QueryLicense() *LicenseQuery {
	return NewTOTPSecretClient(_m.config).QueryLicense(_m)
}

// Update returns a builder for updating this TOTPSecret.
// Note that you need to call TOTPSecret.Unwrap() before calling this method if this TOTPSecret
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TOTPSecret) Update() *TOTPSecretUpdateOne {
	return NewTOTPSecretClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TOTPSecret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TOTPSecret) Unwrap() *TOTPSecret {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TOTPSecret is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TOTPSecret) String() string {
	var builder strings.Builder
	builder.WriteString("TOTPSecret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("encrypted_secret=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedSecret))
	builder.WriteString(", ")
	builder.WriteString("account_label=")
	builder.WriteString(_m.AccountLabel)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TOTPSecrets is a parsable slice of TOTPSecret.
type TOTPSecrets []*TOTPSecret
