// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/license"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
	"github.com/oioio-space/maldev/internal/manager/store/ent/totpsecret"
)

// TOTPSecretUpdate is the builder for updating TOTPSecret entities.
type TOTPSecretUpdate struct {
	config
	hooks    []Hook
	mutation *TOTPSecretMutation
}

// Where appends a list predicates to the TOTPSecretUpdate builder.
func (_u *TOTPSecretUpdate) Where(ps ...predicate.TOTPSecret) *TOTPSecretUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEncryptedSecret sets the "encrypted_secret" field.
func (_u *TOTPSecretUpdate) SetEncryptedSecret(v []byte) *TOTPSecretUpdate {
	_u.mutation.SetEncryptedSecret(v)
	return _u
}

// SetAccountLabel sets the "account_label" field.
func (_u *TOTPSecretUpdate) SetAccountLabel(v string) *TOTPSecretUpdate {
	_u.mutation.SetAccountLabel(v)
	return _u
}

// SetNillableAccountLabel sets the "account_label" field if the given value is not nil.
func (_u *TOTPSecretUpdate) SetNillableAccountLabel(v *string) *TOTPSecretUpdate {
	if v != nil {
		_u.SetAccountLabel(*v)
	}
	return _u
}

// SetLicenseID sets the "license" edge to the License entity by ID.
func (_u *TOTPSecretUpdate) SetLicenseID(id uuid.UUID) *TOTPSecretUpdate {
	_u.mutation.SetLicenseID(id)
	return _u
}

// SetNillableLicenseID sets the "license" edge to the License entity by ID if the given value is not nil.
func (_u *TOTPSecretUpdate) SetNillableLicenseID(id *uuid.UUID) *TOTPSecretUpdate {
	if id != nil {
		_u = _u.SetLicenseID(*id)
	}
	return _u
}

// SetLicense sets the "license" edge to the License entity.
func (_u *TOTPSecretUpdate) SetLicense(v *License) *TOTPSecretUpdate {
	return _u.SetLicenseID(v.ID)
}

// Mutation returns the TOTPSecretMutation object of the builder.
func (_u *TOTPSecretUpdate) Mutation() *TOTPSecretMutation {
	return _u.mutation
}

// ClearLicense clears the "license" edge to the License entity.
func (_u *TOTPSecretUpdate) ClearLicense() *TOTPSecretUpdate {
	_u.mutation.ClearLicense()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TOTPSecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TOTPSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TOTPSecretUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TOTPSecretUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TOTPSecretUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(totpsecret.Table, totpsecret.Columns, sqlgraph.NewFieldSpec(totpsecret.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EncryptedSecret(); ok {
		_spec.SetField(totpsecret.FieldEncryptedSecret, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.AccountLabel(); ok {
		_spec.SetField(totpsecret.FieldAccountLabel, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpsecret.LicenseTable,
			Columns: []string{totpsecret.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpsecret.LicenseTable,
			Columns: []string{totpsecret.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{totpsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TOTPSecretUpdateOne is the builder for updating a single TOTPSecret entity.
type TOTPSecretUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TOTPSecretMutation
}

// SetEncryptedSecret sets the "encrypted_secret" field.
func (_u *TOTPSecretUpdateOne) SetEncryptedSecret(v []byte) *TOTPSecretUpdateOne {
	_u.mutation.SetEncryptedSecret(v)
	return _u
}

// SetAccountLabel sets the "account_label" field.
func (_u *TOTPSecretUpdateOne) SetAccountLabel(v string) *TOTPSecretUpdateOne {
	_u.mutation.SetAccountLabel(v)
	return _u
}

// SetNillableAccountLabel sets the "account_label" field if the given value is not nil.
func (_u *TOTPSecretUpdateOne) SetNillableAccountLabel(v *string) *TOTPSecretUpdateOne {
	if v != nil {
		_u.SetAccountLabel(*v)
	}
	return _u
}

// SetLicenseID sets the "license" edge to the License entity by ID.
func (_u *TOTPSecretUpdateOne) SetLicenseID(id uuid.UUID) *TOTPSecretUpdateOne {
	_u.mutation.SetLicenseID(id)
	return _u
}

// SetNillableLicenseID sets the "license" edge to the License entity by ID if the given value is not nil.
func (_u *TOTPSecretUpdateOne) SetNillableLicenseID(id *uuid.UUID) *TOTPSecretUpdateOne {
	if id != nil {
		_u = _u.SetLicenseID(*id)
	}
	return _u
}

// SetLicense sets the "license" edge to the License entity.
func (_u *TOTPSecretUpdateOne) SetLicense(v *License) *TOTPSecretUpdateOne {
	return _u.SetLicenseID(v.ID)
}

// Mutation returns the TOTPSecretMutation object of the builder.
func (_u *TOTPSecretUpdateOne) Mutation() *TOTPSecretMutation {
	return _u.mutation
}

// ClearLicense clears the "license" edge to the License entity.
func (_u *TOTPSecretUpdateOne) ClearLicense() *TOTPSecretUpdateOne {
	_u.mutation.ClearLicense()
	return _u
}

// Where appends a list predicates to the TOTPSecretUpdate builder.
func (_u *TOTPSecretUpdateOne) Where(ps ...predicate.TOTPSecret) *TOTPSecretUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TOTPSecretUpdateOne) Select(field string, fields ...string) *TOTPSecretUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TOTPSecret entity.
func (_u *TOTPSecretUpdateOne) Save(ctx context.Context) (*TOTPSecret, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TOTPSecretUpdateOne) SaveX(ctx context.Context) *TOTPSecret {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TOTPSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TOTPSecretUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TOTPSecretUpdateOne) sqlSave(ctx context.Context) (_node *TOTPSecret, err error) {
	_spec := sqlgraph.NewUpdateSpec(totpsecret.Table, totpsecret.Columns, sqlgraph.NewFieldSpec(totpsecret.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TOTPSecret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, totpsecret.FieldID)
		for _, f := range fields {
			if !totpsecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != totpsecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EncryptedSecret(); ok {
		_spec.SetField(totpsecret.FieldEncryptedSecret, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.AccountLabel(); ok {
		_spec.SetField(totpsecret.FieldAccountLabel, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpsecret.LicenseTable,
			Columns: []string{totpsecret.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   totpsecret.LicenseTable,
			Columns: []string{totpsecret.LicenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TOTPSecret{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{totpsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
