// Code generated by ent, DO NOT EDIT.

package revocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldID, id))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldReason, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedBy applies equality check predicate on the "revoked_by" field. It's identical to RevokedByEQ.
func RevokedBy(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedBy, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldContainsFold(FieldReason, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedByEQ applies the EQ predicate on the "revoked_by" field.
func RevokedByEQ(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedBy, v))
}

// RevokedByNEQ applies the NEQ predicate on the "revoked_by" field.
func RevokedByNEQ(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldRevokedBy, v))
}

// RevokedByIn applies the In predicate on the "revoked_by" field.
func RevokedByIn(vs ...string) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldRevokedBy, vs...))
}

// RevokedByNotIn applies the NotIn predicate on the "revoked_by" field.
func RevokedByNotIn(vs ...string) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldRevokedBy, vs...))
}

// RevokedByGT applies the GT predicate on the "revoked_by" field.
func RevokedByGT(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldRevokedBy, v))
}

// RevokedByGTE applies the GTE predicate on the "revoked_by" field.
func RevokedByGTE(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldRevokedBy, v))
}

// RevokedByLT applies the LT predicate on the "revoked_by" field.
func RevokedByLT(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldRevokedBy, v))
}

// RevokedByLTE applies the LTE predicate on the "revoked_by" field.
func RevokedByLTE(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldRevokedBy, v))
}

// RevokedByContains applies the Contains predicate on the "revoked_by" field.
func RevokedByContains(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldContains(FieldRevokedBy, v))
}

// RevokedByHasPrefix applies the HasPrefix predicate on the "revoked_by" field.
func RevokedByHasPrefix(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldHasPrefix(FieldRevokedBy, v))
}

// RevokedByHasSuffix applies the HasSuffix predicate on the "revoked_by" field.
func RevokedByHasSuffix(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldHasSuffix(FieldRevokedBy, v))
}

// RevokedByEqualFold applies the EqualFold predicate on the "revoked_by" field.
func RevokedByEqualFold(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldEqualFold(FieldRevokedBy, v))
}

// RevokedByContainsFold applies the ContainsFold predicate on the "revoked_by" field.
func RevokedByContainsFold(v string) predicate.Revocation {
	return predicate.Revocation(sql.FieldContainsFold(FieldRevokedBy, v))
}

// HasLicense applies the HasEdge predicate on the "license" edge.
func HasLicense() predicate.Revocation {
	return predicate.Revocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, LicenseTable, LicenseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLicenseWith applies the HasEdge predicate on the "license" edge with a given conditions (other predicates).
func HasLicenseWith(preds ...predicate.License) predicate.Revocation {
	return predicate.Revocation(func(s *sql.Selector) {
		step := newLicenseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.NotPredicates(p))
}
