// Code generated by ent, DO NOT EDIT.

package probetoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the probetoken type in the database.
	Label = "probe_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldRemoteAddr holds the string denoting the remote_addr field in the database.
	FieldRemoteAddr = "remote_addr"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldArch holds the string denoting the arch field in the database.
	FieldArch = "arch"
	// FieldCPUBrand holds the string denoting the cpu_brand field in the database.
	FieldCPUBrand = "cpu_brand"
	// FieldLocalHex holds the string denoting the local_hex field in the database.
	FieldLocalHex = "local_hex"
	// FieldCompositeHex holds the string denoting the composite_hex field in the database.
	FieldCompositeHex = "composite_hex"
	// Table holds the table name of the probetoken in the database.
	Table = "probe_tokens"
)

// Columns holds all SQL columns for probetoken fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldUsedAt,
	FieldRemoteAddr,
	FieldHostname,
	FieldOs,
	FieldArch,
	FieldCPUBrand,
	FieldLocalHex,
	FieldCompositeHex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ProbeToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByRemoteAddr orders the results by the remote_addr field.
func ByRemoteAddr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteAddr, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByArch orders the results by the arch field.
func ByArch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArch, opts...).ToFunc()
}

// ByCPUBrand orders the results by the cpu_brand field.
func ByCPUBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCPUBrand, opts...).ToFunc()
}

// ByLocalHex orders the results by the local_hex field.
func ByLocalHex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalHex, opts...).ToFunc()
}

// ByCompositeHex orders the results by the composite_hex field.
func ByCompositeHex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompositeHex, opts...).ToFunc()
}
