// Code generated by ent, DO NOT EDIT.

package probetoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldExpiresAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldUsedAt, v))
}

// RemoteAddr applies equality check predicate on the "remote_addr" field. It's identical to RemoteAddrEQ.
func RemoteAddr(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldRemoteAddr, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldHostname, v))
}

// Os applies equality check predicate on the "os" field. It's identical to OsEQ.
func Os(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldOs, v))
}

// Arch applies equality check predicate on the "arch" field. It's identical to ArchEQ.
func Arch(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldArch, v))
}

// CPUBrand applies equality check predicate on the "cpu_brand" field. It's identical to CPUBrandEQ.
func CPUBrand(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCPUBrand, v))
}

// LocalHex applies equality check predicate on the "local_hex" field. It's identical to LocalHexEQ.
func LocalHex(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldLocalHex, v))
}

// CompositeHex applies equality check predicate on the "composite_hex" field. It's identical to CompositeHexEQ.
func CompositeHex(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCompositeHex, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldLabel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldExpiresAt, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldUsedAt))
}

// RemoteAddrEQ applies the EQ predicate on the "remote_addr" field.
func RemoteAddrEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldRemoteAddr, v))
}

// RemoteAddrNEQ applies the NEQ predicate on the "remote_addr" field.
func RemoteAddrNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldRemoteAddr, v))
}

// RemoteAddrIn applies the In predicate on the "remote_addr" field.
func RemoteAddrIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldRemoteAddr, vs...))
}

// RemoteAddrNotIn applies the NotIn predicate on the "remote_addr" field.
func RemoteAddrNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldRemoteAddr, vs...))
}

// RemoteAddrGT applies the GT predicate on the "remote_addr" field.
func RemoteAddrGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldRemoteAddr, v))
}

// RemoteAddrGTE applies the GTE predicate on the "remote_addr" field.
func RemoteAddrGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldRemoteAddr, v))
}

// RemoteAddrLT applies the LT predicate on the "remote_addr" field.
func RemoteAddrLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldRemoteAddr, v))
}

// RemoteAddrLTE applies the LTE predicate on the "remote_addr" field.
func RemoteAddrLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldRemoteAddr, v))
}

// RemoteAddrContains applies the Contains predicate on the "remote_addr" field.
func RemoteAddrContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldRemoteAddr, v))
}

// RemoteAddrHasPrefix applies the HasPrefix predicate on the "remote_addr" field.
func RemoteAddrHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldRemoteAddr, v))
}

// RemoteAddrHasSuffix applies the HasSuffix predicate on the "remote_addr" field.
func RemoteAddrHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldRemoteAddr, v))
}

// RemoteAddrIsNil applies the IsNil predicate on the "remote_addr" field.
func RemoteAddrIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldRemoteAddr))
}

// RemoteAddrNotNil applies the NotNil predicate on the "remote_addr" field.
func RemoteAddrNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldRemoteAddr))
}

// RemoteAddrEqualFold applies the EqualFold predicate on the "remote_addr" field.
func RemoteAddrEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldRemoteAddr, v))
}

// RemoteAddrContainsFold applies the ContainsFold predicate on the "remote_addr" field.
func RemoteAddrContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldRemoteAddr, v))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameIsNil applies the IsNil predicate on the "hostname" field.
func HostnameIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldHostname))
}

// HostnameNotNil applies the NotNil predicate on the "hostname" field.
func HostnameNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldHostname))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldHostname, v))
}

// OsEQ applies the EQ predicate on the "os" field.
func OsEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldOs, v))
}

// OsNEQ applies the NEQ predicate on the "os" field.
func OsNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldOs, v))
}

// OsIn applies the In predicate on the "os" field.
func OsIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldOs, vs...))
}

// OsNotIn applies the NotIn predicate on the "os" field.
func OsNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldOs, vs...))
}

// OsGT applies the GT predicate on the "os" field.
func OsGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldOs, v))
}

// OsGTE applies the GTE predicate on the "os" field.
func OsGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldOs, v))
}

// OsLT applies the LT predicate on the "os" field.
func OsLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldOs, v))
}

// OsLTE applies the LTE predicate on the "os" field.
func OsLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldOs, v))
}

// OsContains applies the Contains predicate on the "os" field.
func OsContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldOs, v))
}

// OsHasPrefix applies the HasPrefix predicate on the "os" field.
func OsHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldOs, v))
}

// OsHasSuffix applies the HasSuffix predicate on the "os" field.
func OsHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldOs, v))
}

// OsIsNil applies the IsNil predicate on the "os" field.
func OsIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldOs))
}

// OsNotNil applies the NotNil predicate on the "os" field.
func OsNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldOs))
}

// OsEqualFold applies the EqualFold predicate on the "os" field.
func OsEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldOs, v))
}

// OsContainsFold applies the ContainsFold predicate on the "os" field.
func OsContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldOs, v))
}

// ArchEQ applies the EQ predicate on the "arch" field.
func ArchEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldArch, v))
}

// ArchNEQ applies the NEQ predicate on the "arch" field.
func ArchNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldArch, v))
}

// ArchIn applies the In predicate on the "arch" field.
func ArchIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldArch, vs...))
}

// ArchNotIn applies the NotIn predicate on the "arch" field.
func ArchNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldArch, vs...))
}

// ArchGT applies the GT predicate on the "arch" field.
func ArchGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldArch, v))
}

// ArchGTE applies the GTE predicate on the "arch" field.
func ArchGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldArch, v))
}

// ArchLT applies the LT predicate on the "arch" field.
func ArchLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldArch, v))
}

// ArchLTE applies the LTE predicate on the "arch" field.
func ArchLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldArch, v))
}

// ArchContains applies the Contains predicate on the "arch" field.
func ArchContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldArch, v))
}

// ArchHasPrefix applies the HasPrefix predicate on the "arch" field.
func ArchHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldArch, v))
}

// ArchHasSuffix applies the HasSuffix predicate on the "arch" field.
func ArchHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldArch, v))
}

// ArchIsNil applies the IsNil predicate on the "arch" field.
func ArchIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldArch))
}

// ArchNotNil applies the NotNil predicate on the "arch" field.
func ArchNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldArch))
}

// ArchEqualFold applies the EqualFold predicate on the "arch" field.
func ArchEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldArch, v))
}

// ArchContainsFold applies the ContainsFold predicate on the "arch" field.
func ArchContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldArch, v))
}

// CPUBrandEQ applies the EQ predicate on the "cpu_brand" field.
func CPUBrandEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCPUBrand, v))
}

// CPUBrandNEQ applies the NEQ predicate on the "cpu_brand" field.
func CPUBrandNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldCPUBrand, v))
}

// CPUBrandIn applies the In predicate on the "cpu_brand" field.
func CPUBrandIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldCPUBrand, vs...))
}

// CPUBrandNotIn applies the NotIn predicate on the "cpu_brand" field.
func CPUBrandNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldCPUBrand, vs...))
}

// CPUBrandGT applies the GT predicate on the "cpu_brand" field.
func CPUBrandGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldCPUBrand, v))
}

// CPUBrandGTE applies the GTE predicate on the "cpu_brand" field.
func CPUBrandGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldCPUBrand, v))
}

// CPUBrandLT applies the LT predicate on the "cpu_brand" field.
func CPUBrandLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldCPUBrand, v))
}

// CPUBrandLTE applies the LTE predicate on the "cpu_brand" field.
func CPUBrandLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldCPUBrand, v))
}

// CPUBrandContains applies the Contains predicate on the "cpu_brand" field.
func CPUBrandContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldCPUBrand, v))
}

// CPUBrandHasPrefix applies the HasPrefix predicate on the "cpu_brand" field.
func CPUBrandHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldCPUBrand, v))
}

// CPUBrandHasSuffix applies the HasSuffix predicate on the "cpu_brand" field.
func CPUBrandHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldCPUBrand, v))
}

// CPUBrandIsNil applies the IsNil predicate on the "cpu_brand" field.
func CPUBrandIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldCPUBrand))
}

// CPUBrandNotNil applies the NotNil predicate on the "cpu_brand" field.
func CPUBrandNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldCPUBrand))
}

// CPUBrandEqualFold applies the EqualFold predicate on the "cpu_brand" field.
func CPUBrandEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldCPUBrand, v))
}

// CPUBrandContainsFold applies the ContainsFold predicate on the "cpu_brand" field.
func CPUBrandContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldCPUBrand, v))
}

// LocalHexEQ applies the EQ predicate on the "local_hex" field.
func LocalHexEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldLocalHex, v))
}

// LocalHexNEQ applies the NEQ predicate on the "local_hex" field.
func LocalHexNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldLocalHex, v))
}

// LocalHexIn applies the In predicate on the "local_hex" field.
func LocalHexIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldLocalHex, vs...))
}

// LocalHexNotIn applies the NotIn predicate on the "local_hex" field.
func LocalHexNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldLocalHex, vs...))
}

// LocalHexGT applies the GT predicate on the "local_hex" field.
func LocalHexGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldLocalHex, v))
}

// LocalHexGTE applies the GTE predicate on the "local_hex" field.
func LocalHexGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldLocalHex, v))
}

// LocalHexLT applies the LT predicate on the "local_hex" field.
func LocalHexLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldLocalHex, v))
}

// LocalHexLTE applies the LTE predicate on the "local_hex" field.
func LocalHexLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldLocalHex, v))
}

// LocalHexContains applies the Contains predicate on the "local_hex" field.
func LocalHexContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldLocalHex, v))
}

// LocalHexHasPrefix applies the HasPrefix predicate on the "local_hex" field.
func LocalHexHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldLocalHex, v))
}

// LocalHexHasSuffix applies the HasSuffix predicate on the "local_hex" field.
func LocalHexHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldLocalHex, v))
}

// LocalHexIsNil applies the IsNil predicate on the "local_hex" field.
func LocalHexIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldLocalHex))
}

// LocalHexNotNil applies the NotNil predicate on the "local_hex" field.
func LocalHexNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldLocalHex))
}

// LocalHexEqualFold applies the EqualFold predicate on the "local_hex" field.
func LocalHexEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldLocalHex, v))
}

// LocalHexContainsFold applies the ContainsFold predicate on the "local_hex" field.
func LocalHexContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldLocalHex, v))
}

// CompositeHexEQ applies the EQ predicate on the "composite_hex" field.
func CompositeHexEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEQ(FieldCompositeHex, v))
}

// CompositeHexNEQ applies the NEQ predicate on the "composite_hex" field.
func CompositeHexNEQ(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNEQ(FieldCompositeHex, v))
}

// CompositeHexIn applies the In predicate on the "composite_hex" field.
func CompositeHexIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIn(FieldCompositeHex, vs...))
}

// CompositeHexNotIn applies the NotIn predicate on the "composite_hex" field.
func CompositeHexNotIn(vs ...string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotIn(FieldCompositeHex, vs...))
}

// CompositeHexGT applies the GT predicate on the "composite_hex" field.
func CompositeHexGT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGT(FieldCompositeHex, v))
}

// CompositeHexGTE applies the GTE predicate on the "composite_hex" field.
func CompositeHexGTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldGTE(FieldCompositeHex, v))
}

// CompositeHexLT applies the LT predicate on the "composite_hex" field.
func CompositeHexLT(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLT(FieldCompositeHex, v))
}

// CompositeHexLTE applies the LTE predicate on the "composite_hex" field.
func CompositeHexLTE(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldLTE(FieldCompositeHex, v))
}

// CompositeHexContains applies the Contains predicate on the "composite_hex" field.
func CompositeHexContains(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContains(FieldCompositeHex, v))
}

// CompositeHexHasPrefix applies the HasPrefix predicate on the "composite_hex" field.
func CompositeHexHasPrefix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasPrefix(FieldCompositeHex, v))
}

// CompositeHexHasSuffix applies the HasSuffix predicate on the "composite_hex" field.
func CompositeHexHasSuffix(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldHasSuffix(FieldCompositeHex, v))
}

// CompositeHexIsNil applies the IsNil predicate on the "composite_hex" field.
func CompositeHexIsNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldIsNull(FieldCompositeHex))
}

// CompositeHexNotNil applies the NotNil predicate on the "composite_hex" field.
func CompositeHexNotNil() predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldNotNull(FieldCompositeHex))
}

// CompositeHexEqualFold applies the EqualFold predicate on the "composite_hex" field.
func CompositeHexEqualFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldEqualFold(FieldCompositeHex, v))
}

// CompositeHexContainsFold applies the ContainsFold predicate on the "composite_hex" field.
func CompositeHexContainsFold(v string) predicate.ProbeToken {
	return predicate.ProbeToken(sql.FieldContainsFold(FieldCompositeHex, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProbeToken) predicate.ProbeToken {
	return predicate.ProbeToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProbeToken) predicate.ProbeToken {
	return predicate.ProbeToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProbeToken) predicate.ProbeToken {
	return predicate.ProbeToken(sql.NotPredicates(p))
}
