// Code generated by ent, DO NOT EDIT.

package serverconfig

import (
	"entgo.io/ent/dialect/sql"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldID, id))
}

// RevocationListen applies equality check predicate on the "revocation_listen" field. It's identical to RevocationListenEQ.
func RevocationListen(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationListen, v))
}

// RevocationTLSCert applies equality check predicate on the "revocation_tls_cert" field. It's identical to RevocationTLSCertEQ.
func RevocationTLSCert(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationTLSCert, v))
}

// RevocationTLSKey applies equality check predicate on the "revocation_tls_key" field. It's identical to RevocationTLSKeyEQ.
func RevocationTLSKey(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationTLSKey, v))
}

// RevocationAdminTokenEnc applies equality check predicate on the "revocation_admin_token_enc" field. It's identical to RevocationAdminTokenEncEQ.
func RevocationAdminTokenEnc(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationAdminTokenEnc, v))
}

// RevocationPath applies equality check predicate on the "revocation_path" field. It's identical to RevocationPathEQ.
func RevocationPath(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationPath, v))
}

// HeartbeatListen applies equality check predicate on the "heartbeat_listen" field. It's identical to HeartbeatListenEQ.
func HeartbeatListen(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatListen, v))
}

// HeartbeatTLSCert applies equality check predicate on the "heartbeat_tls_cert" field. It's identical to HeartbeatTLSCertEQ.
func HeartbeatTLSCert(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSKey applies equality check predicate on the "heartbeat_tls_key" field. It's identical to HeartbeatTLSKeyEQ.
func HeartbeatTLSKey(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatTLSKey, v))
}

// HeartbeatPath applies equality check predicate on the "heartbeat_path" field. It's identical to HeartbeatPathEQ.
func HeartbeatPath(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatPath, v))
}

// ProbeListen applies equality check predicate on the "probe_listen" field. It's identical to ProbeListenEQ.
func ProbeListen(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeListen, v))
}

// ProbeTLSCert applies equality check predicate on the "probe_tls_cert" field. It's identical to ProbeTLSCertEQ.
func ProbeTLSCert(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeTLSCert, v))
}

// ProbeTLSKey applies equality check predicate on the "probe_tls_key" field. It's identical to ProbeTLSKeyEQ.
func ProbeTLSKey(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeTLSKey, v))
}

// ProbeDefaultTTLSeconds applies equality check predicate on the "probe_default_ttl_seconds" field. It's identical to ProbeDefaultTTLSecondsEQ.
func ProbeDefaultTTLSeconds(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeDefaultTTLSeconds, v))
}

// RevocationListenEQ applies the EQ predicate on the "revocation_listen" field.
func RevocationListenEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationListen, v))
}

// RevocationListenNEQ applies the NEQ predicate on the "revocation_listen" field.
func RevocationListenNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldRevocationListen, v))
}

// RevocationListenIn applies the In predicate on the "revocation_listen" field.
func RevocationListenIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldRevocationListen, vs...))
}

// RevocationListenNotIn applies the NotIn predicate on the "revocation_listen" field.
func RevocationListenNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldRevocationListen, vs...))
}

// RevocationListenGT applies the GT predicate on the "revocation_listen" field.
func RevocationListenGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldRevocationListen, v))
}

// RevocationListenGTE applies the GTE predicate on the "revocation_listen" field.
func RevocationListenGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldRevocationListen, v))
}

// RevocationListenLT applies the LT predicate on the "revocation_listen" field.
func RevocationListenLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldRevocationListen, v))
}

// RevocationListenLTE applies the LTE predicate on the "revocation_listen" field.
func RevocationListenLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldRevocationListen, v))
}

// RevocationListenContains applies the Contains predicate on the "revocation_listen" field.
func RevocationListenContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldRevocationListen, v))
}

// RevocationListenHasPrefix applies the HasPrefix predicate on the "revocation_listen" field.
func RevocationListenHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldRevocationListen, v))
}

// RevocationListenHasSuffix applies the HasSuffix predicate on the "revocation_listen" field.
func RevocationListenHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldRevocationListen, v))
}

// RevocationListenEqualFold applies the EqualFold predicate on the "revocation_listen" field.
func RevocationListenEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldRevocationListen, v))
}

// RevocationListenContainsFold applies the ContainsFold predicate on the "revocation_listen" field.
func RevocationListenContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldRevocationListen, v))
}

// RevocationTLSCertEQ applies the EQ predicate on the "revocation_tls_cert" field.
func RevocationTLSCertEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationTLSCert, v))
}

// RevocationTLSCertNEQ applies the NEQ predicate on the "revocation_tls_cert" field.
func RevocationTLSCertNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldRevocationTLSCert, v))
}

// RevocationTLSCertIn applies the In predicate on the "revocation_tls_cert" field.
func RevocationTLSCertIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldRevocationTLSCert, vs...))
}

// RevocationTLSCertNotIn applies the NotIn predicate on the "revocation_tls_cert" field.
func RevocationTLSCertNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldRevocationTLSCert, vs...))
}

// RevocationTLSCertGT applies the GT predicate on the "revocation_tls_cert" field.
func RevocationTLSCertGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldRevocationTLSCert, v))
}

// RevocationTLSCertGTE applies the GTE predicate on the "revocation_tls_cert" field.
func RevocationTLSCertGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldRevocationTLSCert, v))
}

// RevocationTLSCertLT applies the LT predicate on the "revocation_tls_cert" field.
func RevocationTLSCertLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldRevocationTLSCert, v))
}

// RevocationTLSCertLTE applies the LTE predicate on the "revocation_tls_cert" field.
func RevocationTLSCertLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldRevocationTLSCert, v))
}

// RevocationTLSCertContains applies the Contains predicate on the "revocation_tls_cert" field.
func RevocationTLSCertContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldRevocationTLSCert, v))
}

// RevocationTLSCertHasPrefix applies the HasPrefix predicate on the "revocation_tls_cert" field.
func RevocationTLSCertHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldRevocationTLSCert, v))
}

// RevocationTLSCertHasSuffix applies the HasSuffix predicate on the "revocation_tls_cert" field.
func RevocationTLSCertHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldRevocationTLSCert, v))
}

// RevocationTLSCertIsNil applies the IsNil predicate on the "revocation_tls_cert" field.
func RevocationTLSCertIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldRevocationTLSCert))
}

// RevocationTLSCertNotNil applies the NotNil predicate on the "revocation_tls_cert" field.
func RevocationTLSCertNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldRevocationTLSCert))
}

// RevocationTLSCertEqualFold applies the EqualFold predicate on the "revocation_tls_cert" field.
func RevocationTLSCertEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldRevocationTLSCert, v))
}

// RevocationTLSCertContainsFold applies the ContainsFold predicate on the "revocation_tls_cert" field.
func RevocationTLSCertContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldRevocationTLSCert, v))
}

// RevocationTLSKeyEQ applies the EQ predicate on the "revocation_tls_key" field.
func RevocationTLSKeyEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyNEQ applies the NEQ predicate on the "revocation_tls_key" field.
func RevocationTLSKeyNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyIn applies the In predicate on the "revocation_tls_key" field.
func RevocationTLSKeyIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldRevocationTLSKey, vs...))
}

// RevocationTLSKeyNotIn applies the NotIn predicate on the "revocation_tls_key" field.
func RevocationTLSKeyNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldRevocationTLSKey, vs...))
}

// RevocationTLSKeyGT applies the GT predicate on the "revocation_tls_key" field.
func RevocationTLSKeyGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyGTE applies the GTE predicate on the "revocation_tls_key" field.
func RevocationTLSKeyGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyLT applies the LT predicate on the "revocation_tls_key" field.
func RevocationTLSKeyLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyLTE applies the LTE predicate on the "revocation_tls_key" field.
func RevocationTLSKeyLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyContains applies the Contains predicate on the "revocation_tls_key" field.
func RevocationTLSKeyContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyHasPrefix applies the HasPrefix predicate on the "revocation_tls_key" field.
func RevocationTLSKeyHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyHasSuffix applies the HasSuffix predicate on the "revocation_tls_key" field.
func RevocationTLSKeyHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyIsNil applies the IsNil predicate on the "revocation_tls_key" field.
func RevocationTLSKeyIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldRevocationTLSKey))
}

// RevocationTLSKeyNotNil applies the NotNil predicate on the "revocation_tls_key" field.
func RevocationTLSKeyNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldRevocationTLSKey))
}

// RevocationTLSKeyEqualFold applies the EqualFold predicate on the "revocation_tls_key" field.
func RevocationTLSKeyEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldRevocationTLSKey, v))
}

// RevocationTLSKeyContainsFold applies the ContainsFold predicate on the "revocation_tls_key" field.
func RevocationTLSKeyContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldRevocationTLSKey, v))
}

// RevocationAdminTokenEncEQ applies the EQ predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncEQ(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncNEQ applies the NEQ predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncNEQ(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncIn applies the In predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncIn(vs ...[]byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldRevocationAdminTokenEnc, vs...))
}

// RevocationAdminTokenEncNotIn applies the NotIn predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncNotIn(vs ...[]byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldRevocationAdminTokenEnc, vs...))
}

// RevocationAdminTokenEncGT applies the GT predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncGT(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncGTE applies the GTE predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncGTE(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncLT applies the LT predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncLT(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncLTE applies the LTE predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncLTE(v []byte) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldRevocationAdminTokenEnc, v))
}

// RevocationAdminTokenEncIsNil applies the IsNil predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldRevocationAdminTokenEnc))
}

// RevocationAdminTokenEncNotNil applies the NotNil predicate on the "revocation_admin_token_enc" field.
func RevocationAdminTokenEncNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldRevocationAdminTokenEnc))
}

// RevocationPathEQ applies the EQ predicate on the "revocation_path" field.
func RevocationPathEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldRevocationPath, v))
}

// RevocationPathNEQ applies the NEQ predicate on the "revocation_path" field.
func RevocationPathNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldRevocationPath, v))
}

// RevocationPathIn applies the In predicate on the "revocation_path" field.
func RevocationPathIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldRevocationPath, vs...))
}

// RevocationPathNotIn applies the NotIn predicate on the "revocation_path" field.
func RevocationPathNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldRevocationPath, vs...))
}

// RevocationPathGT applies the GT predicate on the "revocation_path" field.
func RevocationPathGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldRevocationPath, v))
}

// RevocationPathGTE applies the GTE predicate on the "revocation_path" field.
func RevocationPathGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldRevocationPath, v))
}

// RevocationPathLT applies the LT predicate on the "revocation_path" field.
func RevocationPathLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldRevocationPath, v))
}

// RevocationPathLTE applies the LTE predicate on the "revocation_path" field.
func RevocationPathLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldRevocationPath, v))
}

// RevocationPathContains applies the Contains predicate on the "revocation_path" field.
func RevocationPathContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldRevocationPath, v))
}

// RevocationPathHasPrefix applies the HasPrefix predicate on the "revocation_path" field.
func RevocationPathHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldRevocationPath, v))
}

// RevocationPathHasSuffix applies the HasSuffix predicate on the "revocation_path" field.
func RevocationPathHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldRevocationPath, v))
}

// RevocationPathEqualFold applies the EqualFold predicate on the "revocation_path" field.
func RevocationPathEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldRevocationPath, v))
}

// RevocationPathContainsFold applies the ContainsFold predicate on the "revocation_path" field.
func RevocationPathContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldRevocationPath, v))
}

// HeartbeatListenEQ applies the EQ predicate on the "heartbeat_listen" field.
func HeartbeatListenEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatListen, v))
}

// HeartbeatListenNEQ applies the NEQ predicate on the "heartbeat_listen" field.
func HeartbeatListenNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldHeartbeatListen, v))
}

// HeartbeatListenIn applies the In predicate on the "heartbeat_listen" field.
func HeartbeatListenIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldHeartbeatListen, vs...))
}

// HeartbeatListenNotIn applies the NotIn predicate on the "heartbeat_listen" field.
func HeartbeatListenNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldHeartbeatListen, vs...))
}

// HeartbeatListenGT applies the GT predicate on the "heartbeat_listen" field.
func HeartbeatListenGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldHeartbeatListen, v))
}

// HeartbeatListenGTE applies the GTE predicate on the "heartbeat_listen" field.
func HeartbeatListenGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldHeartbeatListen, v))
}

// HeartbeatListenLT applies the LT predicate on the "heartbeat_listen" field.
func HeartbeatListenLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldHeartbeatListen, v))
}

// HeartbeatListenLTE applies the LTE predicate on the "heartbeat_listen" field.
func HeartbeatListenLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldHeartbeatListen, v))
}

// HeartbeatListenContains applies the Contains predicate on the "heartbeat_listen" field.
func HeartbeatListenContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldHeartbeatListen, v))
}

// HeartbeatListenHasPrefix applies the HasPrefix predicate on the "heartbeat_listen" field.
func HeartbeatListenHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldHeartbeatListen, v))
}

// HeartbeatListenHasSuffix applies the HasSuffix predicate on the "heartbeat_listen" field.
func HeartbeatListenHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldHeartbeatListen, v))
}

// HeartbeatListenEqualFold applies the EqualFold predicate on the "heartbeat_listen" field.
func HeartbeatListenEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldHeartbeatListen, v))
}

// HeartbeatListenContainsFold applies the ContainsFold predicate on the "heartbeat_listen" field.
func HeartbeatListenContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldHeartbeatListen, v))
}

// HeartbeatTLSCertEQ applies the EQ predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertNEQ applies the NEQ predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertIn applies the In predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldHeartbeatTLSCert, vs...))
}

// HeartbeatTLSCertNotIn applies the NotIn predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldHeartbeatTLSCert, vs...))
}

// HeartbeatTLSCertGT applies the GT predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertGTE applies the GTE predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertLT applies the LT predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertLTE applies the LTE predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertContains applies the Contains predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertHasPrefix applies the HasPrefix predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertHasSuffix applies the HasSuffix predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertIsNil applies the IsNil predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldHeartbeatTLSCert))
}

// HeartbeatTLSCertNotNil applies the NotNil predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldHeartbeatTLSCert))
}

// HeartbeatTLSCertEqualFold applies the EqualFold predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSCertContainsFold applies the ContainsFold predicate on the "heartbeat_tls_cert" field.
func HeartbeatTLSCertContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldHeartbeatTLSCert, v))
}

// HeartbeatTLSKeyEQ applies the EQ predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyNEQ applies the NEQ predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyIn applies the In predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldHeartbeatTLSKey, vs...))
}

// HeartbeatTLSKeyNotIn applies the NotIn predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldHeartbeatTLSKey, vs...))
}

// HeartbeatTLSKeyGT applies the GT predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyGTE applies the GTE predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyLT applies the LT predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyLTE applies the LTE predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyContains applies the Contains predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyHasPrefix applies the HasPrefix predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyHasSuffix applies the HasSuffix predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyIsNil applies the IsNil predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldHeartbeatTLSKey))
}

// HeartbeatTLSKeyNotNil applies the NotNil predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldHeartbeatTLSKey))
}

// HeartbeatTLSKeyEqualFold applies the EqualFold predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldHeartbeatTLSKey, v))
}

// HeartbeatTLSKeyContainsFold applies the ContainsFold predicate on the "heartbeat_tls_key" field.
func HeartbeatTLSKeyContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldHeartbeatTLSKey, v))
}

// HeartbeatPathEQ applies the EQ predicate on the "heartbeat_path" field.
func HeartbeatPathEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldHeartbeatPath, v))
}

// HeartbeatPathNEQ applies the NEQ predicate on the "heartbeat_path" field.
func HeartbeatPathNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldHeartbeatPath, v))
}

// HeartbeatPathIn applies the In predicate on the "heartbeat_path" field.
func HeartbeatPathIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldHeartbeatPath, vs...))
}

// HeartbeatPathNotIn applies the NotIn predicate on the "heartbeat_path" field.
func HeartbeatPathNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldHeartbeatPath, vs...))
}

// HeartbeatPathGT applies the GT predicate on the "heartbeat_path" field.
func HeartbeatPathGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldHeartbeatPath, v))
}

// HeartbeatPathGTE applies the GTE predicate on the "heartbeat_path" field.
func HeartbeatPathGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldHeartbeatPath, v))
}

// HeartbeatPathLT applies the LT predicate on the "heartbeat_path" field.
func HeartbeatPathLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldHeartbeatPath, v))
}

// HeartbeatPathLTE applies the LTE predicate on the "heartbeat_path" field.
func HeartbeatPathLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldHeartbeatPath, v))
}

// HeartbeatPathContains applies the Contains predicate on the "heartbeat_path" field.
func HeartbeatPathContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldHeartbeatPath, v))
}

// HeartbeatPathHasPrefix applies the HasPrefix predicate on the "heartbeat_path" field.
func HeartbeatPathHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldHeartbeatPath, v))
}

// HeartbeatPathHasSuffix applies the HasSuffix predicate on the "heartbeat_path" field.
func HeartbeatPathHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldHeartbeatPath, v))
}

// HeartbeatPathEqualFold applies the EqualFold predicate on the "heartbeat_path" field.
func HeartbeatPathEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldHeartbeatPath, v))
}

// HeartbeatPathContainsFold applies the ContainsFold predicate on the "heartbeat_path" field.
func HeartbeatPathContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldHeartbeatPath, v))
}

// ProbeListenEQ applies the EQ predicate on the "probe_listen" field.
func ProbeListenEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeListen, v))
}

// ProbeListenNEQ applies the NEQ predicate on the "probe_listen" field.
func ProbeListenNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldProbeListen, v))
}

// ProbeListenIn applies the In predicate on the "probe_listen" field.
func ProbeListenIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldProbeListen, vs...))
}

// ProbeListenNotIn applies the NotIn predicate on the "probe_listen" field.
func ProbeListenNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldProbeListen, vs...))
}

// ProbeListenGT applies the GT predicate on the "probe_listen" field.
func ProbeListenGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldProbeListen, v))
}

// ProbeListenGTE applies the GTE predicate on the "probe_listen" field.
func ProbeListenGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldProbeListen, v))
}

// ProbeListenLT applies the LT predicate on the "probe_listen" field.
func ProbeListenLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldProbeListen, v))
}

// ProbeListenLTE applies the LTE predicate on the "probe_listen" field.
func ProbeListenLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldProbeListen, v))
}

// ProbeListenContains applies the Contains predicate on the "probe_listen" field.
func ProbeListenContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldProbeListen, v))
}

// ProbeListenHasPrefix applies the HasPrefix predicate on the "probe_listen" field.
func ProbeListenHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldProbeListen, v))
}

// ProbeListenHasSuffix applies the HasSuffix predicate on the "probe_listen" field.
func ProbeListenHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldProbeListen, v))
}

// ProbeListenEqualFold applies the EqualFold predicate on the "probe_listen" field.
func ProbeListenEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldProbeListen, v))
}

// ProbeListenContainsFold applies the ContainsFold predicate on the "probe_listen" field.
func ProbeListenContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldProbeListen, v))
}

// ProbeTLSCertEQ applies the EQ predicate on the "probe_tls_cert" field.
func ProbeTLSCertEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeTLSCert, v))
}

// ProbeTLSCertNEQ applies the NEQ predicate on the "probe_tls_cert" field.
func ProbeTLSCertNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldProbeTLSCert, v))
}

// ProbeTLSCertIn applies the In predicate on the "probe_tls_cert" field.
func ProbeTLSCertIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldProbeTLSCert, vs...))
}

// ProbeTLSCertNotIn applies the NotIn predicate on the "probe_tls_cert" field.
func ProbeTLSCertNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldProbeTLSCert, vs...))
}

// ProbeTLSCertGT applies the GT predicate on the "probe_tls_cert" field.
func ProbeTLSCertGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldProbeTLSCert, v))
}

// ProbeTLSCertGTE applies the GTE predicate on the "probe_tls_cert" field.
func ProbeTLSCertGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldProbeTLSCert, v))
}

// ProbeTLSCertLT applies the LT predicate on the "probe_tls_cert" field.
func ProbeTLSCertLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldProbeTLSCert, v))
}

// ProbeTLSCertLTE applies the LTE predicate on the "probe_tls_cert" field.
func ProbeTLSCertLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldProbeTLSCert, v))
}

// ProbeTLSCertContains applies the Contains predicate on the "probe_tls_cert" field.
func ProbeTLSCertContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldProbeTLSCert, v))
}

// ProbeTLSCertHasPrefix applies the HasPrefix predicate on the "probe_tls_cert" field.
func ProbeTLSCertHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldProbeTLSCert, v))
}

// ProbeTLSCertHasSuffix applies the HasSuffix predicate on the "probe_tls_cert" field.
func ProbeTLSCertHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldProbeTLSCert, v))
}

// ProbeTLSCertIsNil applies the IsNil predicate on the "probe_tls_cert" field.
func ProbeTLSCertIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldProbeTLSCert))
}

// ProbeTLSCertNotNil applies the NotNil predicate on the "probe_tls_cert" field.
func ProbeTLSCertNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldProbeTLSCert))
}

// ProbeTLSCertEqualFold applies the EqualFold predicate on the "probe_tls_cert" field.
func ProbeTLSCertEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldProbeTLSCert, v))
}

// ProbeTLSCertContainsFold applies the ContainsFold predicate on the "probe_tls_cert" field.
func ProbeTLSCertContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldProbeTLSCert, v))
}

// ProbeTLSKeyEQ applies the EQ predicate on the "probe_tls_key" field.
func ProbeTLSKeyEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeTLSKey, v))
}

// ProbeTLSKeyNEQ applies the NEQ predicate on the "probe_tls_key" field.
func ProbeTLSKeyNEQ(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldProbeTLSKey, v))
}

// ProbeTLSKeyIn applies the In predicate on the "probe_tls_key" field.
func ProbeTLSKeyIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldProbeTLSKey, vs...))
}

// ProbeTLSKeyNotIn applies the NotIn predicate on the "probe_tls_key" field.
func ProbeTLSKeyNotIn(vs ...string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldProbeTLSKey, vs...))
}

// ProbeTLSKeyGT applies the GT predicate on the "probe_tls_key" field.
func ProbeTLSKeyGT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldProbeTLSKey, v))
}

// ProbeTLSKeyGTE applies the GTE predicate on the "probe_tls_key" field.
func ProbeTLSKeyGTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldProbeTLSKey, v))
}

// ProbeTLSKeyLT applies the LT predicate on the "probe_tls_key" field.
func ProbeTLSKeyLT(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldProbeTLSKey, v))
}

// ProbeTLSKeyLTE applies the LTE predicate on the "probe_tls_key" field.
func ProbeTLSKeyLTE(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldProbeTLSKey, v))
}

// ProbeTLSKeyContains applies the Contains predicate on the "probe_tls_key" field.
func ProbeTLSKeyContains(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContains(FieldProbeTLSKey, v))
}

// ProbeTLSKeyHasPrefix applies the HasPrefix predicate on the "probe_tls_key" field.
func ProbeTLSKeyHasPrefix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasPrefix(FieldProbeTLSKey, v))
}

// ProbeTLSKeyHasSuffix applies the HasSuffix predicate on the "probe_tls_key" field.
func ProbeTLSKeyHasSuffix(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldHasSuffix(FieldProbeTLSKey, v))
}

// ProbeTLSKeyIsNil applies the IsNil predicate on the "probe_tls_key" field.
func ProbeTLSKeyIsNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIsNull(FieldProbeTLSKey))
}

// ProbeTLSKeyNotNil applies the NotNil predicate on the "probe_tls_key" field.
func ProbeTLSKeyNotNil() predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotNull(FieldProbeTLSKey))
}

// ProbeTLSKeyEqualFold applies the EqualFold predicate on the "probe_tls_key" field.
func ProbeTLSKeyEqualFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEqualFold(FieldProbeTLSKey, v))
}

// ProbeTLSKeyContainsFold applies the ContainsFold predicate on the "probe_tls_key" field.
func ProbeTLSKeyContainsFold(v string) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldContainsFold(FieldProbeTLSKey, v))
}

// ProbeDefaultTTLSecondsEQ applies the EQ predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsEQ(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldEQ(FieldProbeDefaultTTLSeconds, v))
}

// ProbeDefaultTTLSecondsNEQ applies the NEQ predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsNEQ(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNEQ(FieldProbeDefaultTTLSeconds, v))
}

// ProbeDefaultTTLSecondsIn applies the In predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsIn(vs ...int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldIn(FieldProbeDefaultTTLSeconds, vs...))
}

// ProbeDefaultTTLSecondsNotIn applies the NotIn predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsNotIn(vs ...int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldNotIn(FieldProbeDefaultTTLSeconds, vs...))
}

// ProbeDefaultTTLSecondsGT applies the GT predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsGT(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGT(FieldProbeDefaultTTLSeconds, v))
}

// ProbeDefaultTTLSecondsGTE applies the GTE predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsGTE(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldGTE(FieldProbeDefaultTTLSeconds, v))
}

// ProbeDefaultTTLSecondsLT applies the LT predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsLT(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLT(FieldProbeDefaultTTLSeconds, v))
}

// ProbeDefaultTTLSecondsLTE applies the LTE predicate on the "probe_default_ttl_seconds" field.
func ProbeDefaultTTLSecondsLTE(v int) predicate.ServerConfig {
	return predicate.ServerConfig(sql.FieldLTE(FieldProbeDefaultTTLSeconds, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServerConfig) predicate.ServerConfig {
	return predicate.ServerConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServerConfig) predicate.ServerConfig {
	return predicate.ServerConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServerConfig) predicate.ServerConfig {
	return predicate.ServerConfig(sql.NotPredicates(p))
}
