// Code generated by ent, DO NOT EDIT.

package setting

import (
	"entgo.io/ent/dialect/sql"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldID, id))
}

// DefaultIssuerName applies equality check predicate on the "default_issuer_name" field. It's identical to DefaultIssuerNameEQ.
func DefaultIssuerName(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldDefaultIssuerName, v))
}

// DefaultTTLSeconds applies equality check predicate on the "default_ttl_seconds" field. It's identical to DefaultTTLSecondsEQ.
func DefaultTTLSeconds(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldDefaultTTLSeconds, v))
}

// OperatorName applies equality check predicate on the "operator_name" field. It's identical to OperatorNameEQ.
func OperatorName(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldOperatorName, v))
}

// AutoStartServers applies equality check predicate on the "auto_start_servers" field. It's identical to AutoStartServersEQ.
func AutoStartServers(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldAutoStartServers, v))
}

// ConfirmQuitWithServers applies equality check predicate on the "confirm_quit_with_servers" field. It's identical to ConfirmQuitWithServersEQ.
func ConfirmQuitWithServers(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldConfirmQuitWithServers, v))
}

// StopServersOnExit applies equality check predicate on the "stop_servers_on_exit" field. It's identical to StopServersOnExitEQ.
func StopServersOnExit(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldStopServersOnExit, v))
}

// BoldSaturated applies equality check predicate on the "bold_saturated" field. It's identical to BoldSaturatedEQ.
func BoldSaturated(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldBoldSaturated, v))
}

// ComfortDensity applies equality check predicate on the "comfort_density" field. It's identical to ComfortDensityEQ.
func ComfortDensity(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldComfortDensity, v))
}

// TimestampsLocal applies equality check predicate on the "timestamps_local" field. It's identical to TimestampsLocalEQ.
func TimestampsLocal(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldTimestampsLocal, v))
}

// KekSalt applies equality check predicate on the "kek_salt" field. It's identical to KekSaltEQ.
func KekSalt(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldKekSalt, v))
}

// KekCanary applies equality check predicate on the "kek_canary" field. It's identical to KekCanaryEQ.
func KekCanary(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldKekCanary, v))
}

// DefaultIssuerNameEQ applies the EQ predicate on the "default_issuer_name" field.
func DefaultIssuerNameEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameNEQ applies the NEQ predicate on the "default_issuer_name" field.
func DefaultIssuerNameNEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameIn applies the In predicate on the "default_issuer_name" field.
func DefaultIssuerNameIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldDefaultIssuerName, vs...))
}

// DefaultIssuerNameNotIn applies the NotIn predicate on the "default_issuer_name" field.
func DefaultIssuerNameNotIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldDefaultIssuerName, vs...))
}

// DefaultIssuerNameGT applies the GT predicate on the "default_issuer_name" field.
func DefaultIssuerNameGT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameGTE applies the GTE predicate on the "default_issuer_name" field.
func DefaultIssuerNameGTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameLT applies the LT predicate on the "default_issuer_name" field.
func DefaultIssuerNameLT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameLTE applies the LTE predicate on the "default_issuer_name" field.
func DefaultIssuerNameLTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameContains applies the Contains predicate on the "default_issuer_name" field.
func DefaultIssuerNameContains(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContains(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameHasPrefix applies the HasPrefix predicate on the "default_issuer_name" field.
func DefaultIssuerNameHasPrefix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasPrefix(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameHasSuffix applies the HasSuffix predicate on the "default_issuer_name" field.
func DefaultIssuerNameHasSuffix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasSuffix(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameIsNil applies the IsNil predicate on the "default_issuer_name" field.
func DefaultIssuerNameIsNil() predicate.Setting {
	return predicate.Setting(sql.FieldIsNull(FieldDefaultIssuerName))
}

// DefaultIssuerNameNotNil applies the NotNil predicate on the "default_issuer_name" field.
func DefaultIssuerNameNotNil() predicate.Setting {
	return predicate.Setting(sql.FieldNotNull(FieldDefaultIssuerName))
}

// DefaultIssuerNameEqualFold applies the EqualFold predicate on the "default_issuer_name" field.
func DefaultIssuerNameEqualFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldDefaultIssuerName, v))
}

// DefaultIssuerNameContainsFold applies the ContainsFold predicate on the "default_issuer_name" field.
func DefaultIssuerNameContainsFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldDefaultIssuerName, v))
}

// DefaultAudienceIsNil applies the IsNil predicate on the "default_audience" field.
func DefaultAudienceIsNil() predicate.Setting {
	return predicate.Setting(sql.FieldIsNull(FieldDefaultAudience))
}

// DefaultAudienceNotNil applies the NotNil predicate on the "default_audience" field.
func DefaultAudienceNotNil() predicate.Setting {
	return predicate.Setting(sql.FieldNotNull(FieldDefaultAudience))
}

// DefaultTTLSecondsEQ applies the EQ predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldDefaultTTLSeconds, v))
}

// DefaultTTLSecondsNEQ applies the NEQ predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsNEQ(v int) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldDefaultTTLSeconds, v))
}

// DefaultTTLSecondsIn applies the In predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldDefaultTTLSeconds, vs...))
}

// DefaultTTLSecondsNotIn applies the NotIn predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsNotIn(vs ...int) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldDefaultTTLSeconds, vs...))
}

// DefaultTTLSecondsGT applies the GT predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsGT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldDefaultTTLSeconds, v))
}

// DefaultTTLSecondsGTE applies the GTE predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsGTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldDefaultTTLSeconds, v))
}

// DefaultTTLSecondsLT applies the LT predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsLT(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldDefaultTTLSeconds, v))
}

// DefaultTTLSecondsLTE applies the LTE predicate on the "default_ttl_seconds" field.
func DefaultTTLSecondsLTE(v int) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldDefaultTTLSeconds, v))
}

// DefaultArgonPresetEQ applies the EQ predicate on the "default_argon_preset" field.
func DefaultArgonPresetEQ(v DefaultArgonPreset) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldDefaultArgonPreset, v))
}

// DefaultArgonPresetNEQ applies the NEQ predicate on the "default_argon_preset" field.
func DefaultArgonPresetNEQ(v DefaultArgonPreset) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldDefaultArgonPreset, v))
}

// DefaultArgonPresetIn applies the In predicate on the "default_argon_preset" field.
func DefaultArgonPresetIn(vs ...DefaultArgonPreset) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldDefaultArgonPreset, vs...))
}

// DefaultArgonPresetNotIn applies the NotIn predicate on the "default_argon_preset" field.
func DefaultArgonPresetNotIn(vs ...DefaultArgonPreset) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldDefaultArgonPreset, vs...))
}

// OperatorNameEQ applies the EQ predicate on the "operator_name" field.
func OperatorNameEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldOperatorName, v))
}

// OperatorNameNEQ applies the NEQ predicate on the "operator_name" field.
func OperatorNameNEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldOperatorName, v))
}

// OperatorNameIn applies the In predicate on the "operator_name" field.
func OperatorNameIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldOperatorName, vs...))
}

// OperatorNameNotIn applies the NotIn predicate on the "operator_name" field.
func OperatorNameNotIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldOperatorName, vs...))
}

// OperatorNameGT applies the GT predicate on the "operator_name" field.
func OperatorNameGT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldOperatorName, v))
}

// OperatorNameGTE applies the GTE predicate on the "operator_name" field.
func OperatorNameGTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldOperatorName, v))
}

// OperatorNameLT applies the LT predicate on the "operator_name" field.
func OperatorNameLT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldOperatorName, v))
}

// OperatorNameLTE applies the LTE predicate on the "operator_name" field.
func OperatorNameLTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldOperatorName, v))
}

// OperatorNameContains applies the Contains predicate on the "operator_name" field.
func OperatorNameContains(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContains(FieldOperatorName, v))
}

// OperatorNameHasPrefix applies the HasPrefix predicate on the "operator_name" field.
func OperatorNameHasPrefix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasPrefix(FieldOperatorName, v))
}

// OperatorNameHasSuffix applies the HasSuffix predicate on the "operator_name" field.
func OperatorNameHasSuffix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasSuffix(FieldOperatorName, v))
}

// OperatorNameIsNil applies the IsNil predicate on the "operator_name" field.
func OperatorNameIsNil() predicate.Setting {
	return predicate.Setting(sql.FieldIsNull(FieldOperatorName))
}

// OperatorNameNotNil applies the NotNil predicate on the "operator_name" field.
func OperatorNameNotNil() predicate.Setting {
	return predicate.Setting(sql.FieldNotNull(FieldOperatorName))
}

// OperatorNameEqualFold applies the EqualFold predicate on the "operator_name" field.
func OperatorNameEqualFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldOperatorName, v))
}

// OperatorNameContainsFold applies the ContainsFold predicate on the "operator_name" field.
func OperatorNameContainsFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldOperatorName, v))
}

// AutoStartServersEQ applies the EQ predicate on the "auto_start_servers" field.
func AutoStartServersEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldAutoStartServers, v))
}

// AutoStartServersNEQ applies the NEQ predicate on the "auto_start_servers" field.
func AutoStartServersNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldAutoStartServers, v))
}

// ConfirmQuitWithServersEQ applies the EQ predicate on the "confirm_quit_with_servers" field.
func ConfirmQuitWithServersEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldConfirmQuitWithServers, v))
}

// ConfirmQuitWithServersNEQ applies the NEQ predicate on the "confirm_quit_with_servers" field.
func ConfirmQuitWithServersNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldConfirmQuitWithServers, v))
}

// StopServersOnExitEQ applies the EQ predicate on the "stop_servers_on_exit" field.
func StopServersOnExitEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldStopServersOnExit, v))
}

// StopServersOnExitNEQ applies the NEQ predicate on the "stop_servers_on_exit" field.
func StopServersOnExitNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldStopServersOnExit, v))
}

// ThemeEQ applies the EQ predicate on the "theme" field.
func ThemeEQ(v Theme) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldTheme, v))
}

// ThemeNEQ applies the NEQ predicate on the "theme" field.
func ThemeNEQ(v Theme) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldTheme, v))
}

// ThemeIn applies the In predicate on the "theme" field.
func ThemeIn(vs ...Theme) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldTheme, vs...))
}

// ThemeNotIn applies the NotIn predicate on the "theme" field.
func ThemeNotIn(vs ...Theme) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldTheme, vs...))
}

// BoldSaturatedEQ applies the EQ predicate on the "bold_saturated" field.
func BoldSaturatedEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldBoldSaturated, v))
}

// BoldSaturatedNEQ applies the NEQ predicate on the "bold_saturated" field.
func BoldSaturatedNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldBoldSaturated, v))
}

// ComfortDensityEQ applies the EQ predicate on the "comfort_density" field.
func ComfortDensityEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldComfortDensity, v))
}

// ComfortDensityNEQ applies the NEQ predicate on the "comfort_density" field.
func ComfortDensityNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldComfortDensity, v))
}

// TimestampsLocalEQ applies the EQ predicate on the "timestamps_local" field.
func TimestampsLocalEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldTimestampsLocal, v))
}

// TimestampsLocalNEQ applies the NEQ predicate on the "timestamps_local" field.
func TimestampsLocalNEQ(v bool) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldTimestampsLocal, v))
}

// KekSaltEQ applies the EQ predicate on the "kek_salt" field.
func KekSaltEQ(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldKekSalt, v))
}

// KekSaltNEQ applies the NEQ predicate on the "kek_salt" field.
func KekSaltNEQ(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldKekSalt, v))
}

// KekSaltIn applies the In predicate on the "kek_salt" field.
func KekSaltIn(vs ...[]byte) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldKekSalt, vs...))
}

// KekSaltNotIn applies the NotIn predicate on the "kek_salt" field.
func KekSaltNotIn(vs ...[]byte) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldKekSalt, vs...))
}

// KekSaltGT applies the GT predicate on the "kek_salt" field.
func KekSaltGT(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldKekSalt, v))
}

// KekSaltGTE applies the GTE predicate on the "kek_salt" field.
func KekSaltGTE(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldKekSalt, v))
}

// KekSaltLT applies the LT predicate on the "kek_salt" field.
func KekSaltLT(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldKekSalt, v))
}

// KekSaltLTE applies the LTE predicate on the "kek_salt" field.
func KekSaltLTE(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldKekSalt, v))
}

// KekCanaryEQ applies the EQ predicate on the "kek_canary" field.
func KekCanaryEQ(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldKekCanary, v))
}

// KekCanaryNEQ applies the NEQ predicate on the "kek_canary" field.
func KekCanaryNEQ(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldKekCanary, v))
}

// KekCanaryIn applies the In predicate on the "kek_canary" field.
func KekCanaryIn(vs ...[]byte) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldKekCanary, vs...))
}

// KekCanaryNotIn applies the NotIn predicate on the "kek_canary" field.
func KekCanaryNotIn(vs ...[]byte) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldKekCanary, vs...))
}

// KekCanaryGT applies the GT predicate on the "kek_canary" field.
func KekCanaryGT(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldKekCanary, v))
}

// KekCanaryGTE applies the GTE predicate on the "kek_canary" field.
func KekCanaryGTE(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldKekCanary, v))
}

// KekCanaryLT applies the LT predicate on the "kek_canary" field.
func KekCanaryLT(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldKekCanary, v))
}

// KekCanaryLTE applies the LTE predicate on the "kek_canary" field.
func KekCanaryLTE(v []byte) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldKekCanary, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.NotPredicates(p))
}
