package tui

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"

	"github.com/oioio-space/maldev/internal/manager/service"
)

// exportTOTPPDF renders a one-page PDF for the given TOTP secret view and
// writes it to path. The file is created with mode 0600.
//
// Page layout (A4 portrait):
//   - Header:     "TOTP Secret · <issuer name>" in bold
//   - Body:       account label, cleartext secret (monospace), otpauth URI
//   - QR image:   embedded from QRImagePNG (centre-aligned)
//   - Footer:     "Generated by license-manager · <RFC3339 date>"
func exportTOTPPDF(v *service.TOTPSecretView, path string) error {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	pageW, _ := pdf.GetPageSize()
	contentW := pageW - 40 // left+right margins = 40 mm

	// ── Header ───────────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(contentW, 10, "TOTP Secret · license-manager", "", 1, "C", false, 0, "")
	pdf.Ln(4)

	// ── Divider line ─────────────────────────────────────────────────────────
	pdf.SetDrawColor(180, 180, 180)
	pdf.Line(20, pdf.GetY(), pageW-20, pdf.GetY())
	pdf.Ln(6)

	// ── Body fields ──────────────────────────────────────────────────────────
	fieldLabel := func(label string) {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(80, 80, 80)
		pdf.CellFormat(40, 7, label, "", 0, "L", false, 0, "")
	}
	fieldValue := func(value string) {
		pdf.SetFont("Courier", "", 10)
		pdf.SetTextColor(20, 20, 20)
		pdf.MultiCell(contentW-40, 7, value, "", "L", false)
	}

	fieldLabel("Account:")
	fieldValue(v.AccountLabel)

	fieldLabel("Secret:")
	fieldValue(v.Secret)

	fieldLabel("URI:")
	pdf.SetFont("Courier", "", 8)
	pdf.SetTextColor(20, 20, 20)
	pdf.MultiCell(contentW-40, 6, v.OtpauthURI, "", "L", false)

	pdf.Ln(6)

	// ── QR code image ────────────────────────────────────────────────────────
	if len(v.QRImagePNG) > 0 {
		imgOpt := gofpdf.ImageOptions{ImageType: "PNG", ReadDpi: true}
		pdf.RegisterImageOptionsReader("qr", imgOpt, bytes.NewReader(v.QRImagePNG))
		// Centre the QR image: 60×60 mm square.
		const qrSize = 60.0
		x := (pageW - qrSize) / 2
		pdf.ImageOptions("qr", x, pdf.GetY(), qrSize, qrSize, false, imgOpt, 0, "")
		pdf.Ln(qrSize + 4)
	}

	// ── Footer ───────────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(130, 130, 130)
	footer := fmt.Sprintf("Generated by license-manager · %s", time.Now().Format(time.RFC3339))
	pdf.CellFormat(contentW, 6, footer, "", 1, "C", false, 0, "")

	return pdf.OutputFileAndClose(path)
}
