// Code generated by ent, DO NOT EDIT.

package totpsecret

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLTE(FieldID, id))
}

// EncryptedSecret applies equality check predicate on the "encrypted_secret" field. It's identical to EncryptedSecretEQ.
func EncryptedSecret(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldEncryptedSecret, v))
}

// AccountLabel applies equality check predicate on the "account_label" field. It's identical to AccountLabelEQ.
func AccountLabel(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldAccountLabel, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldCreatedAt, v))
}

// EncryptedSecretEQ applies the EQ predicate on the "encrypted_secret" field.
func EncryptedSecretEQ(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldEncryptedSecret, v))
}

// EncryptedSecretNEQ applies the NEQ predicate on the "encrypted_secret" field.
func EncryptedSecretNEQ(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNEQ(FieldEncryptedSecret, v))
}

// EncryptedSecretIn applies the In predicate on the "encrypted_secret" field.
func EncryptedSecretIn(vs ...[]byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldIn(FieldEncryptedSecret, vs...))
}

// EncryptedSecretNotIn applies the NotIn predicate on the "encrypted_secret" field.
func EncryptedSecretNotIn(vs ...[]byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNotIn(FieldEncryptedSecret, vs...))
}

// EncryptedSecretGT applies the GT predicate on the "encrypted_secret" field.
func EncryptedSecretGT(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGT(FieldEncryptedSecret, v))
}

// EncryptedSecretGTE applies the GTE predicate on the "encrypted_secret" field.
func EncryptedSecretGTE(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGTE(FieldEncryptedSecret, v))
}

// EncryptedSecretLT applies the LT predicate on the "encrypted_secret" field.
func EncryptedSecretLT(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLT(FieldEncryptedSecret, v))
}

// EncryptedSecretLTE applies the LTE predicate on the "encrypted_secret" field.
func EncryptedSecretLTE(v []byte) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLTE(FieldEncryptedSecret, v))
}

// AccountLabelEQ applies the EQ predicate on the "account_label" field.
func AccountLabelEQ(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldAccountLabel, v))
}

// AccountLabelNEQ applies the NEQ predicate on the "account_label" field.
func AccountLabelNEQ(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNEQ(FieldAccountLabel, v))
}

// AccountLabelIn applies the In predicate on the "account_label" field.
func AccountLabelIn(vs ...string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldIn(FieldAccountLabel, vs...))
}

// AccountLabelNotIn applies the NotIn predicate on the "account_label" field.
func AccountLabelNotIn(vs ...string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNotIn(FieldAccountLabel, vs...))
}

// AccountLabelGT applies the GT predicate on the "account_label" field.
func AccountLabelGT(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGT(FieldAccountLabel, v))
}

// AccountLabelGTE applies the GTE predicate on the "account_label" field.
func AccountLabelGTE(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGTE(FieldAccountLabel, v))
}

// AccountLabelLT applies the LT predicate on the "account_label" field.
func AccountLabelLT(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLT(FieldAccountLabel, v))
}

// AccountLabelLTE applies the LTE predicate on the "account_label" field.
func AccountLabelLTE(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLTE(FieldAccountLabel, v))
}

// AccountLabelContains applies the Contains predicate on the "account_label" field.
func AccountLabelContains(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldContains(FieldAccountLabel, v))
}

// AccountLabelHasPrefix applies the HasPrefix predicate on the "account_label" field.
func AccountLabelHasPrefix(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldHasPrefix(FieldAccountLabel, v))
}

// AccountLabelHasSuffix applies the HasSuffix predicate on the "account_label" field.
func AccountLabelHasSuffix(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldHasSuffix(FieldAccountLabel, v))
}

// AccountLabelEqualFold applies the EqualFold predicate on the "account_label" field.
func AccountLabelEqualFold(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEqualFold(FieldAccountLabel, v))
}

// AccountLabelContainsFold applies the ContainsFold predicate on the "account_label" field.
func AccountLabelContainsFold(v string) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldContainsFold(FieldAccountLabel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.FieldLTE(FieldCreatedAt, v))
}

// HasLicense applies the HasEdge predicate on the "license" edge.
func HasLicense() predicate.TOTPSecret {
	return predicate.TOTPSecret(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LicenseTable, LicenseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLicenseWith applies the HasEdge predicate on the "license" edge with a given conditions (other predicates).
func HasLicenseWith(preds ...predicate.License) predicate.TOTPSecret {
	return predicate.TOTPSecret(func(s *sql.Selector) {
		step := newLicenseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TOTPSecret) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TOTPSecret) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TOTPSecret) predicate.TOTPSecret {
	return predicate.TOTPSecret(sql.NotPredicates(p))
}
