// Code generated by ent, DO NOT EDIT.

package license

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the license type in the database.
	Label = "license"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLicenseUUID holds the string denoting the license_uuid field in the database.
	FieldLicenseUUID = "license_uuid"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldIssuerName holds the string denoting the issuer_name field in the database.
	FieldIssuerName = "issuer_name"
	// FieldAudience holds the string denoting the audience field in the database.
	FieldAudience = "audience"
	// FieldFeatures holds the string denoting the features field in the database.
	FieldFeatures = "features"
	// FieldNotBefore holds the string denoting the not_before field in the database.
	FieldNotBefore = "not_before"
	// FieldNotAfter holds the string denoting the not_after field in the database.
	FieldNotAfter = "not_after"
	// FieldBindingsMeta holds the string denoting the bindings_meta field in the database.
	FieldBindingsMeta = "bindings_meta"
	// FieldPayloadKind holds the string denoting the payload_kind field in the database.
	FieldPayloadKind = "payload_kind"
	// FieldIdentitySha256 holds the string denoting the identity_sha256 field in the database.
	FieldIdentitySha256 = "identity_sha256"
	// FieldBinarySha256 holds the string denoting the binary_sha256 field in the database.
	FieldBinarySha256 = "binary_sha256"
	// FieldPem holds the string denoting the pem field in the database.
	FieldPem = "pem"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReplacesLicenseID holds the string denoting the replaces_license_id field in the database.
	FieldReplacesLicenseID = "replaces_license_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeIssuer holds the string denoting the issuer edge name in mutations.
	EdgeIssuer = "issuer"
	// EdgeTotps holds the string denoting the totps edge name in mutations.
	EdgeTotps = "totps"
	// EdgeRevocation holds the string denoting the revocation edge name in mutations.
	EdgeRevocation = "revocation"
	// Table holds the table name of the license in the database.
	Table = "licenses"
	// IssuerTable is the table that holds the issuer relation/edge.
	IssuerTable = "licenses"
	// IssuerInverseTable is the table name for the Issuer entity.
	// It exists in this package in order to avoid circular dependency with the "issuer" package.
	IssuerInverseTable = "issuers"
	// IssuerColumn is the table column denoting the issuer relation/edge.
	IssuerColumn = "issuer_licenses"
	// TotpsTable is the table that holds the totps relation/edge.
	TotpsTable = "totp_secrets"
	// TotpsInverseTable is the table name for the TOTPSecret entity.
	// It exists in this package in order to avoid circular dependency with the "totpsecret" package.
	TotpsInverseTable = "totp_secrets"
	// TotpsColumn is the table column denoting the totps relation/edge.
	TotpsColumn = "license_totps"
	// RevocationTable is the table that holds the revocation relation/edge.
	RevocationTable = "revocations"
	// RevocationInverseTable is the table name for the Revocation entity.
	// It exists in this package in order to avoid circular dependency with the "revocation" package.
	RevocationInverseTable = "revocations"
	// RevocationColumn is the table column denoting the revocation relation/edge.
	RevocationColumn = "license_revocation"
)

// Columns holds all SQL columns for license fields.
var Columns = []string{
	FieldID,
	FieldLicenseUUID,
	FieldSubject,
	FieldIssuerName,
	FieldAudience,
	FieldFeatures,
	FieldNotBefore,
	FieldNotAfter,
	FieldBindingsMeta,
	FieldPayloadKind,
	FieldIdentitySha256,
	FieldBinarySha256,
	FieldPem,
	FieldStatus,
	FieldReplacesLicenseID,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "licenses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"issuer_licenses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LicenseUUIDValidator is a validator for the "license_uuid" field. It is called by the builders before save.
	LicenseUUIDValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PayloadKind defines the type for the "payload_kind" enum field.
type PayloadKind string

// PayloadKindNone is the default value of the PayloadKind enum.
const DefaultPayloadKind = PayloadKindNone

// PayloadKind values.
const (
	PayloadKindNone      PayloadKind = "none"
	PayloadKindCleartext PayloadKind = "cleartext"
	PayloadKindSealed    PayloadKind = "sealed"
)

func (pk PayloadKind) String() string {
	return string(pk)
}

// PayloadKindValidator is a validator for the "payload_kind" field enum values. It is called by the builders before save.
func PayloadKindValidator(pk PayloadKind) error {
	switch pk {
	case PayloadKindNone, PayloadKindCleartext, PayloadKindSealed:
		return nil
	default:
		return fmt.Errorf("license: invalid enum value for payload_kind field: %q", pk)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive     Status = "active"
	StatusRevoked    Status = "revoked"
	StatusExpired    Status = "expired"
	StatusSuperseded Status = "superseded"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusRevoked, StatusExpired, StatusSuperseded:
		return nil
	default:
		return fmt.Errorf("license: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the License queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLicenseUUID orders the results by the license_uuid field.
func ByLicenseUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseUUID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByIssuerName orders the results by the issuer_name field.
func ByIssuerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuerName, opts...).ToFunc()
}

// ByNotBefore orders the results by the not_before field.
func ByNotBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotBefore, opts...).ToFunc()
}

// ByNotAfter orders the results by the not_after field.
func ByNotAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotAfter, opts...).ToFunc()
}

// ByPayloadKind orders the results by the payload_kind field.
func ByPayloadKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadKind, opts...).ToFunc()
}

// ByIdentitySha256 orders the results by the identity_sha256 field.
func ByIdentitySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentitySha256, opts...).ToFunc()
}

// ByBinarySha256 orders the results by the binary_sha256 field.
func ByBinarySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinarySha256, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReplacesLicenseID orders the results by the replaces_license_id field.
func ByReplacesLicenseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplacesLicenseID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByIssuerField orders the results by issuer field.
func ByIssuerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIssuerStep(), sql.OrderByField(field, opts...))
	}
}

// ByTotpsCount orders the results by totps count.
func ByTotpsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTotpsStep(), opts...)
	}
}

// ByTotps orders the results by totps terms.
func ByTotps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTotpsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRevocationField orders the results by revocation field.
func ByRevocationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRevocationStep(), sql.OrderByField(field, opts...))
	}
}
func newIssuerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IssuerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
	)
}
func newTotpsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TotpsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TotpsTable, TotpsColumn),
	)
}
func newRevocationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RevocationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, RevocationTable, RevocationColumn),
	)
}
