// Code generated by ent, DO NOT EDIT.

package license

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/oioio-space/maldev/internal/manager/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.License {
	return predicate.License(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.License {
	return predicate.License(sql.FieldLTE(FieldID, id))
}

// LicenseUUID applies equality check predicate on the "license_uuid" field. It's identical to LicenseUUIDEQ.
func LicenseUUID(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldLicenseUUID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldSubject, v))
}

// IssuerName applies equality check predicate on the "issuer_name" field. It's identical to IssuerNameEQ.
func IssuerName(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldIssuerName, v))
}

// NotBefore applies equality check predicate on the "not_before" field. It's identical to NotBeforeEQ.
func NotBefore(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldNotBefore, v))
}

// NotAfter applies equality check predicate on the "not_after" field. It's identical to NotAfterEQ.
func NotAfter(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldNotAfter, v))
}

// IdentitySha256 applies equality check predicate on the "identity_sha256" field. It's identical to IdentitySha256EQ.
func IdentitySha256(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldIdentitySha256, v))
}

// BinarySha256 applies equality check predicate on the "binary_sha256" field. It's identical to BinarySha256EQ.
func BinarySha256(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldBinarySha256, v))
}

// Pem applies equality check predicate on the "pem" field. It's identical to PemEQ.
func Pem(v []byte) predicate.License {
	return predicate.License(sql.FieldEQ(FieldPem, v))
}

// ReplacesLicenseID applies equality check predicate on the "replaces_license_id" field. It's identical to ReplacesLicenseIDEQ.
func ReplacesLicenseID(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldEQ(FieldReplacesLicenseID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldCreatedAt, v))
}

// LicenseUUIDEQ applies the EQ predicate on the "license_uuid" field.
func LicenseUUIDEQ(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldLicenseUUID, v))
}

// LicenseUUIDNEQ applies the NEQ predicate on the "license_uuid" field.
func LicenseUUIDNEQ(v string) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldLicenseUUID, v))
}

// LicenseUUIDIn applies the In predicate on the "license_uuid" field.
func LicenseUUIDIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldIn(FieldLicenseUUID, vs...))
}

// LicenseUUIDNotIn applies the NotIn predicate on the "license_uuid" field.
func LicenseUUIDNotIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldLicenseUUID, vs...))
}

// LicenseUUIDGT applies the GT predicate on the "license_uuid" field.
func LicenseUUIDGT(v string) predicate.License {
	return predicate.License(sql.FieldGT(FieldLicenseUUID, v))
}

// LicenseUUIDGTE applies the GTE predicate on the "license_uuid" field.
func LicenseUUIDGTE(v string) predicate.License {
	return predicate.License(sql.FieldGTE(FieldLicenseUUID, v))
}

// LicenseUUIDLT applies the LT predicate on the "license_uuid" field.
func LicenseUUIDLT(v string) predicate.License {
	return predicate.License(sql.FieldLT(FieldLicenseUUID, v))
}

// LicenseUUIDLTE applies the LTE predicate on the "license_uuid" field.
func LicenseUUIDLTE(v string) predicate.License {
	return predicate.License(sql.FieldLTE(FieldLicenseUUID, v))
}

// LicenseUUIDContains applies the Contains predicate on the "license_uuid" field.
func LicenseUUIDContains(v string) predicate.License {
	return predicate.License(sql.FieldContains(FieldLicenseUUID, v))
}

// LicenseUUIDHasPrefix applies the HasPrefix predicate on the "license_uuid" field.
func LicenseUUIDHasPrefix(v string) predicate.License {
	return predicate.License(sql.FieldHasPrefix(FieldLicenseUUID, v))
}

// LicenseUUIDHasSuffix applies the HasSuffix predicate on the "license_uuid" field.
func LicenseUUIDHasSuffix(v string) predicate.License {
	return predicate.License(sql.FieldHasSuffix(FieldLicenseUUID, v))
}

// LicenseUUIDEqualFold applies the EqualFold predicate on the "license_uuid" field.
func LicenseUUIDEqualFold(v string) predicate.License {
	return predicate.License(sql.FieldEqualFold(FieldLicenseUUID, v))
}

// LicenseUUIDContainsFold applies the ContainsFold predicate on the "license_uuid" field.
func LicenseUUIDContainsFold(v string) predicate.License {
	return predicate.License(sql.FieldContainsFold(FieldLicenseUUID, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.License {
	return predicate.License(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.License {
	return predicate.License(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.License {
	return predicate.License(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.License {
	return predicate.License(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.License {
	return predicate.License(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.License {
	return predicate.License(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.License {
	return predicate.License(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.License {
	return predicate.License(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.License {
	return predicate.License(sql.FieldContainsFold(FieldSubject, v))
}

// IssuerNameEQ applies the EQ predicate on the "issuer_name" field.
func IssuerNameEQ(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldIssuerName, v))
}

// IssuerNameNEQ applies the NEQ predicate on the "issuer_name" field.
func IssuerNameNEQ(v string) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldIssuerName, v))
}

// IssuerNameIn applies the In predicate on the "issuer_name" field.
func IssuerNameIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldIn(FieldIssuerName, vs...))
}

// IssuerNameNotIn applies the NotIn predicate on the "issuer_name" field.
func IssuerNameNotIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldIssuerName, vs...))
}

// IssuerNameGT applies the GT predicate on the "issuer_name" field.
func IssuerNameGT(v string) predicate.License {
	return predicate.License(sql.FieldGT(FieldIssuerName, v))
}

// IssuerNameGTE applies the GTE predicate on the "issuer_name" field.
func IssuerNameGTE(v string) predicate.License {
	return predicate.License(sql.FieldGTE(FieldIssuerName, v))
}

// IssuerNameLT applies the LT predicate on the "issuer_name" field.
func IssuerNameLT(v string) predicate.License {
	return predicate.License(sql.FieldLT(FieldIssuerName, v))
}

// IssuerNameLTE applies the LTE predicate on the "issuer_name" field.
func IssuerNameLTE(v string) predicate.License {
	return predicate.License(sql.FieldLTE(FieldIssuerName, v))
}

// IssuerNameContains applies the Contains predicate on the "issuer_name" field.
func IssuerNameContains(v string) predicate.License {
	return predicate.License(sql.FieldContains(FieldIssuerName, v))
}

// IssuerNameHasPrefix applies the HasPrefix predicate on the "issuer_name" field.
func IssuerNameHasPrefix(v string) predicate.License {
	return predicate.License(sql.FieldHasPrefix(FieldIssuerName, v))
}

// IssuerNameHasSuffix applies the HasSuffix predicate on the "issuer_name" field.
func IssuerNameHasSuffix(v string) predicate.License {
	return predicate.License(sql.FieldHasSuffix(FieldIssuerName, v))
}

// IssuerNameIsNil applies the IsNil predicate on the "issuer_name" field.
func IssuerNameIsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldIssuerName))
}

// IssuerNameNotNil applies the NotNil predicate on the "issuer_name" field.
func IssuerNameNotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldIssuerName))
}

// IssuerNameEqualFold applies the EqualFold predicate on the "issuer_name" field.
func IssuerNameEqualFold(v string) predicate.License {
	return predicate.License(sql.FieldEqualFold(FieldIssuerName, v))
}

// IssuerNameContainsFold applies the ContainsFold predicate on the "issuer_name" field.
func IssuerNameContainsFold(v string) predicate.License {
	return predicate.License(sql.FieldContainsFold(FieldIssuerName, v))
}

// AudienceIsNil applies the IsNil predicate on the "audience" field.
func AudienceIsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldAudience))
}

// AudienceNotNil applies the NotNil predicate on the "audience" field.
func AudienceNotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldAudience))
}

// FeaturesIsNil applies the IsNil predicate on the "features" field.
func FeaturesIsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldFeatures))
}

// FeaturesNotNil applies the NotNil predicate on the "features" field.
func FeaturesNotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldFeatures))
}

// NotBeforeEQ applies the EQ predicate on the "not_before" field.
func NotBeforeEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldNotBefore, v))
}

// NotBeforeNEQ applies the NEQ predicate on the "not_before" field.
func NotBeforeNEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldNotBefore, v))
}

// NotBeforeIn applies the In predicate on the "not_before" field.
func NotBeforeIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldIn(FieldNotBefore, vs...))
}

// NotBeforeNotIn applies the NotIn predicate on the "not_before" field.
func NotBeforeNotIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldNotBefore, vs...))
}

// NotBeforeGT applies the GT predicate on the "not_before" field.
func NotBeforeGT(v time.Time) predicate.License {
	return predicate.License(sql.FieldGT(FieldNotBefore, v))
}

// NotBeforeGTE applies the GTE predicate on the "not_before" field.
func NotBeforeGTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldGTE(FieldNotBefore, v))
}

// NotBeforeLT applies the LT predicate on the "not_before" field.
func NotBeforeLT(v time.Time) predicate.License {
	return predicate.License(sql.FieldLT(FieldNotBefore, v))
}

// NotBeforeLTE applies the LTE predicate on the "not_before" field.
func NotBeforeLTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldLTE(FieldNotBefore, v))
}

// NotAfterEQ applies the EQ predicate on the "not_after" field.
func NotAfterEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldNotAfter, v))
}

// NotAfterNEQ applies the NEQ predicate on the "not_after" field.
func NotAfterNEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldNotAfter, v))
}

// NotAfterIn applies the In predicate on the "not_after" field.
func NotAfterIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldIn(FieldNotAfter, vs...))
}

// NotAfterNotIn applies the NotIn predicate on the "not_after" field.
func NotAfterNotIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldNotAfter, vs...))
}

// NotAfterGT applies the GT predicate on the "not_after" field.
func NotAfterGT(v time.Time) predicate.License {
	return predicate.License(sql.FieldGT(FieldNotAfter, v))
}

// NotAfterGTE applies the GTE predicate on the "not_after" field.
func NotAfterGTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldGTE(FieldNotAfter, v))
}

// NotAfterLT applies the LT predicate on the "not_after" field.
func NotAfterLT(v time.Time) predicate.License {
	return predicate.License(sql.FieldLT(FieldNotAfter, v))
}

// NotAfterLTE applies the LTE predicate on the "not_after" field.
func NotAfterLTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldLTE(FieldNotAfter, v))
}

// BindingsMetaIsNil applies the IsNil predicate on the "bindings_meta" field.
func BindingsMetaIsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldBindingsMeta))
}

// BindingsMetaNotNil applies the NotNil predicate on the "bindings_meta" field.
func BindingsMetaNotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldBindingsMeta))
}

// PayloadKindEQ applies the EQ predicate on the "payload_kind" field.
func PayloadKindEQ(v PayloadKind) predicate.License {
	return predicate.License(sql.FieldEQ(FieldPayloadKind, v))
}

// PayloadKindNEQ applies the NEQ predicate on the "payload_kind" field.
func PayloadKindNEQ(v PayloadKind) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldPayloadKind, v))
}

// PayloadKindIn applies the In predicate on the "payload_kind" field.
func PayloadKindIn(vs ...PayloadKind) predicate.License {
	return predicate.License(sql.FieldIn(FieldPayloadKind, vs...))
}

// PayloadKindNotIn applies the NotIn predicate on the "payload_kind" field.
func PayloadKindNotIn(vs ...PayloadKind) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldPayloadKind, vs...))
}

// IdentitySha256EQ applies the EQ predicate on the "identity_sha256" field.
func IdentitySha256EQ(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldIdentitySha256, v))
}

// IdentitySha256NEQ applies the NEQ predicate on the "identity_sha256" field.
func IdentitySha256NEQ(v string) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldIdentitySha256, v))
}

// IdentitySha256In applies the In predicate on the "identity_sha256" field.
func IdentitySha256In(vs ...string) predicate.License {
	return predicate.License(sql.FieldIn(FieldIdentitySha256, vs...))
}

// IdentitySha256NotIn applies the NotIn predicate on the "identity_sha256" field.
func IdentitySha256NotIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldIdentitySha256, vs...))
}

// IdentitySha256GT applies the GT predicate on the "identity_sha256" field.
func IdentitySha256GT(v string) predicate.License {
	return predicate.License(sql.FieldGT(FieldIdentitySha256, v))
}

// IdentitySha256GTE applies the GTE predicate on the "identity_sha256" field.
func IdentitySha256GTE(v string) predicate.License {
	return predicate.License(sql.FieldGTE(FieldIdentitySha256, v))
}

// IdentitySha256LT applies the LT predicate on the "identity_sha256" field.
func IdentitySha256LT(v string) predicate.License {
	return predicate.License(sql.FieldLT(FieldIdentitySha256, v))
}

// IdentitySha256LTE applies the LTE predicate on the "identity_sha256" field.
func IdentitySha256LTE(v string) predicate.License {
	return predicate.License(sql.FieldLTE(FieldIdentitySha256, v))
}

// IdentitySha256Contains applies the Contains predicate on the "identity_sha256" field.
func IdentitySha256Contains(v string) predicate.License {
	return predicate.License(sql.FieldContains(FieldIdentitySha256, v))
}

// IdentitySha256HasPrefix applies the HasPrefix predicate on the "identity_sha256" field.
func IdentitySha256HasPrefix(v string) predicate.License {
	return predicate.License(sql.FieldHasPrefix(FieldIdentitySha256, v))
}

// IdentitySha256HasSuffix applies the HasSuffix predicate on the "identity_sha256" field.
func IdentitySha256HasSuffix(v string) predicate.License {
	return predicate.License(sql.FieldHasSuffix(FieldIdentitySha256, v))
}

// IdentitySha256IsNil applies the IsNil predicate on the "identity_sha256" field.
func IdentitySha256IsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldIdentitySha256))
}

// IdentitySha256NotNil applies the NotNil predicate on the "identity_sha256" field.
func IdentitySha256NotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldIdentitySha256))
}

// IdentitySha256EqualFold applies the EqualFold predicate on the "identity_sha256" field.
func IdentitySha256EqualFold(v string) predicate.License {
	return predicate.License(sql.FieldEqualFold(FieldIdentitySha256, v))
}

// IdentitySha256ContainsFold applies the ContainsFold predicate on the "identity_sha256" field.
func IdentitySha256ContainsFold(v string) predicate.License {
	return predicate.License(sql.FieldContainsFold(FieldIdentitySha256, v))
}

// BinarySha256EQ applies the EQ predicate on the "binary_sha256" field.
func BinarySha256EQ(v string) predicate.License {
	return predicate.License(sql.FieldEQ(FieldBinarySha256, v))
}

// BinarySha256NEQ applies the NEQ predicate on the "binary_sha256" field.
func BinarySha256NEQ(v string) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldBinarySha256, v))
}

// BinarySha256In applies the In predicate on the "binary_sha256" field.
func BinarySha256In(vs ...string) predicate.License {
	return predicate.License(sql.FieldIn(FieldBinarySha256, vs...))
}

// BinarySha256NotIn applies the NotIn predicate on the "binary_sha256" field.
func BinarySha256NotIn(vs ...string) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldBinarySha256, vs...))
}

// BinarySha256GT applies the GT predicate on the "binary_sha256" field.
func BinarySha256GT(v string) predicate.License {
	return predicate.License(sql.FieldGT(FieldBinarySha256, v))
}

// BinarySha256GTE applies the GTE predicate on the "binary_sha256" field.
func BinarySha256GTE(v string) predicate.License {
	return predicate.License(sql.FieldGTE(FieldBinarySha256, v))
}

// BinarySha256LT applies the LT predicate on the "binary_sha256" field.
func BinarySha256LT(v string) predicate.License {
	return predicate.License(sql.FieldLT(FieldBinarySha256, v))
}

// BinarySha256LTE applies the LTE predicate on the "binary_sha256" field.
func BinarySha256LTE(v string) predicate.License {
	return predicate.License(sql.FieldLTE(FieldBinarySha256, v))
}

// BinarySha256Contains applies the Contains predicate on the "binary_sha256" field.
func BinarySha256Contains(v string) predicate.License {
	return predicate.License(sql.FieldContains(FieldBinarySha256, v))
}

// BinarySha256HasPrefix applies the HasPrefix predicate on the "binary_sha256" field.
func BinarySha256HasPrefix(v string) predicate.License {
	return predicate.License(sql.FieldHasPrefix(FieldBinarySha256, v))
}

// BinarySha256HasSuffix applies the HasSuffix predicate on the "binary_sha256" field.
func BinarySha256HasSuffix(v string) predicate.License {
	return predicate.License(sql.FieldHasSuffix(FieldBinarySha256, v))
}

// BinarySha256IsNil applies the IsNil predicate on the "binary_sha256" field.
func BinarySha256IsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldBinarySha256))
}

// BinarySha256NotNil applies the NotNil predicate on the "binary_sha256" field.
func BinarySha256NotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldBinarySha256))
}

// BinarySha256EqualFold applies the EqualFold predicate on the "binary_sha256" field.
func BinarySha256EqualFold(v string) predicate.License {
	return predicate.License(sql.FieldEqualFold(FieldBinarySha256, v))
}

// BinarySha256ContainsFold applies the ContainsFold predicate on the "binary_sha256" field.
func BinarySha256ContainsFold(v string) predicate.License {
	return predicate.License(sql.FieldContainsFold(FieldBinarySha256, v))
}

// PemEQ applies the EQ predicate on the "pem" field.
func PemEQ(v []byte) predicate.License {
	return predicate.License(sql.FieldEQ(FieldPem, v))
}

// PemNEQ applies the NEQ predicate on the "pem" field.
func PemNEQ(v []byte) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldPem, v))
}

// PemIn applies the In predicate on the "pem" field.
func PemIn(vs ...[]byte) predicate.License {
	return predicate.License(sql.FieldIn(FieldPem, vs...))
}

// PemNotIn applies the NotIn predicate on the "pem" field.
func PemNotIn(vs ...[]byte) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldPem, vs...))
}

// PemGT applies the GT predicate on the "pem" field.
func PemGT(v []byte) predicate.License {
	return predicate.License(sql.FieldGT(FieldPem, v))
}

// PemGTE applies the GTE predicate on the "pem" field.
func PemGTE(v []byte) predicate.License {
	return predicate.License(sql.FieldGTE(FieldPem, v))
}

// PemLT applies the LT predicate on the "pem" field.
func PemLT(v []byte) predicate.License {
	return predicate.License(sql.FieldLT(FieldPem, v))
}

// PemLTE applies the LTE predicate on the "pem" field.
func PemLTE(v []byte) predicate.License {
	return predicate.License(sql.FieldLTE(FieldPem, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.License {
	return predicate.License(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.License {
	return predicate.License(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldStatus, vs...))
}

// ReplacesLicenseIDEQ applies the EQ predicate on the "replaces_license_id" field.
func ReplacesLicenseIDEQ(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldEQ(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDNEQ applies the NEQ predicate on the "replaces_license_id" field.
func ReplacesLicenseIDNEQ(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDIn applies the In predicate on the "replaces_license_id" field.
func ReplacesLicenseIDIn(vs ...uuid.UUID) predicate.License {
	return predicate.License(sql.FieldIn(FieldReplacesLicenseID, vs...))
}

// ReplacesLicenseIDNotIn applies the NotIn predicate on the "replaces_license_id" field.
func ReplacesLicenseIDNotIn(vs ...uuid.UUID) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldReplacesLicenseID, vs...))
}

// ReplacesLicenseIDGT applies the GT predicate on the "replaces_license_id" field.
func ReplacesLicenseIDGT(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldGT(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDGTE applies the GTE predicate on the "replaces_license_id" field.
func ReplacesLicenseIDGTE(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldGTE(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDLT applies the LT predicate on the "replaces_license_id" field.
func ReplacesLicenseIDLT(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldLT(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDLTE applies the LTE predicate on the "replaces_license_id" field.
func ReplacesLicenseIDLTE(v uuid.UUID) predicate.License {
	return predicate.License(sql.FieldLTE(FieldReplacesLicenseID, v))
}

// ReplacesLicenseIDIsNil applies the IsNil predicate on the "replaces_license_id" field.
func ReplacesLicenseIDIsNil() predicate.License {
	return predicate.License(sql.FieldIsNull(FieldReplacesLicenseID))
}

// ReplacesLicenseIDNotNil applies the NotNil predicate on the "replaces_license_id" field.
func ReplacesLicenseIDNotNil() predicate.License {
	return predicate.License(sql.FieldNotNull(FieldReplacesLicenseID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.License {
	return predicate.License(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.License {
	return predicate.License(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.License {
	return predicate.License(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.License {
	return predicate.License(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.License {
	return predicate.License(sql.FieldLTE(FieldCreatedAt, v))
}

// HasIssuer applies the HasEdge predicate on the "issuer" edge.
func HasIssuer() predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IssuerTable, IssuerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuerWith applies the HasEdge predicate on the "issuer" edge with a given conditions (other predicates).
func HasIssuerWith(preds ...predicate.Issuer) predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := newIssuerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTotps applies the HasEdge predicate on the "totps" edge.
func HasTotps() predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TotpsTable, TotpsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTotpsWith applies the HasEdge predicate on the "totps" edge with a given conditions (other predicates).
func HasTotpsWith(preds ...predicate.TOTPSecret) predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := newTotpsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevocation applies the HasEdge predicate on the "revocation" edge.
func HasRevocation() predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, RevocationTable, RevocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevocationWith applies the HasEdge predicate on the "revocation" edge with a given conditions (other predicates).
func HasRevocationWith(preds ...predicate.Revocation) predicate.License {
	return predicate.License(func(s *sql.Selector) {
		step := newRevocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.License) predicate.License {
	return predicate.License(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.License) predicate.License {
	return predicate.License(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.License) predicate.License {
	return predicate.License(sql.NotPredicates(p))
}
